// Generated by AshTypescript
// Do not edit this file manually





export type UUID = string;
export type UUIDv7 = string;

// Organization Schema
export type OrganizationResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "description" | "domain";
  id: UUIDv7;
  name: string | null;
  description: string | null;
  domain: string | null;
};



// User Schema
export type UserResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "firstName" | "lastName" | "email";
  id: UUID;
  firstName: string | null;
  lastName: string | null;
  email: string;
};



// Preference Schema
export type PreferenceResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "value";
  id: UUIDv7;
  name: string | null;
  value: string | null;
};



// Petition Schema
export type PetitionResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "description" | "status";
  id: UUIDv7;
  title: string | null;
  description: string | null;
  status: string | null;
};



// Comment Schema
export type CommentResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "text" | "sentiment";
  id: UUIDv7;
  text: string | null;
  sentiment: string | null;
};









export type OrganizationFilterInput = {
  and?: Array<OrganizationFilterInput>;
  or?: Array<OrganizationFilterInput>;
  not?: Array<OrganizationFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  domain?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };



};
export type UserFilterInput = {
  and?: Array<UserFilterInput>;
  or?: Array<UserFilterInput>;
  not?: Array<UserFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  firstName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  lastName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  email?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };



};
export type PreferenceFilterInput = {
  and?: Array<PreferenceFilterInput>;
  or?: Array<PreferenceFilterInput>;
  not?: Array<PreferenceFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  value?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };



};
export type PetitionFilterInput = {
  and?: Array<PetitionFilterInput>;
  or?: Array<PetitionFilterInput>;
  not?: Array<PetitionFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  status?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };



};
export type CommentFilterInput = {
  and?: Array<CommentFilterInput>;
  or?: Array<CommentFilterInput>;
  not?: Array<CommentFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  text?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  sentiment?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };



};


// Utility Types

// Resource schema constraint
type TypedSchema = {
  __type: "Resource" | "TypedStruct" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends UnionSchema["__primitiveFields"]
      ? FieldSelection[FieldIndex] extends keyof UnionSchema
        ? { [P in FieldSelection[FieldIndex]]: UnionSchema[FieldSelection[FieldIndex]] }
        : never
      : FieldSelection[FieldIndex] extends Record<string, any>
        ? {
            [UnionKey in keyof FieldSelection[FieldIndex]]: UnionKey extends keyof UnionSchema
              ? UnionSchema[UnionKey] extends { __type: "TypedMap"; __primitiveFields: any }
                ? UnionSchema[UnionKey]
                : UnionSchema[UnionKey] extends TypedSchema
                  ? InferResult<UnionSchema[UnionKey], FieldSelection[FieldIndex][UnionKey]>
                  : never
              : never;
          }
        : never;
  }[number]
>;

type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

type ComplexFieldSelection<T extends TypedSchema> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? UnifiedFieldSelection<NonNullable<Resource>>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>>[] }
          : never
      : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
        ? T[K] extends { __array: true }
          ? (PrimitiveFields | {
              [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: T[K][UnionKey] extends { __type: "TypedMap"; __primitiveFields: any }
                ? T[K][UnionKey]["__primitiveFields"][]
                : T[K][UnionKey] extends TypedSchema
                  ? UnifiedFieldSelection<T[K][UnionKey]>[]
                  : never;
            })[]
          : (PrimitiveFields | {
              [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: T[K][UnionKey] extends { __type: "TypedMap"; __primitiveFields: any }
                ? T[K][UnionKey]["__primitiveFields"][]
                : T[K][UnionKey] extends TypedSchema
                  ? UnifiedFieldSelection<T[K][UnionKey]>[]
                  : never;
            })[]
          : NonNullable<T[K]> extends TypedSchema
            ? UnifiedFieldSelection<NonNullable<T[K]>>[]
            : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
type UnifiedFieldSelection<T extends TypedSchema> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T>; // Recursive case

type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? T[K] extends { __array: true }
                ? Array<InferResult<NonNullable<Resource>, Field[K]>>
                : null extends Resource
                  ? InferResult<NonNullable<Resource>, Field[K]> | null
                  : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : T[K] extends { __type: "Union"; __primitiveFields: any }
              ? T[K] extends { __array: true }
                ? {
                    [CurrentK in K]: T[CurrentK] extends { __type: "Union"; __primitiveFields: any }
                      ? Field[CurrentK] extends any[]
                        ? Array<InferUnionFieldValue<T[CurrentK], Field[CurrentK]>> | null
                        : never
                      : never
                  }
                : {
                    [CurrentK in K]: T[CurrentK] extends { __type: "Union"; __primitiveFields: any }
                      ? Field[CurrentK] extends any[]
                        ? InferUnionFieldValue<T[CurrentK], Field[CurrentK]> | null
                        : never
                      : never
                  }
                : NonNullable<T[K]> extends TypedSchema
                  ? null extends T[K]
                    ? InferResult<NonNullable<T[K]>, Field[K]> | null
                    : InferResult<NonNullable<T[K]>, Field[K]>
                  : never
          : never;
      }
    : never;

type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters
type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  false;

// Infer which pagination type is being used from the page config
type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call
 * @example
 * const error: AshRpcError = { type: "validation_error", message: "Something went wrong" }
 */
export type AshRpcError = {
  type: string;
  message: string;
  field?: string;
  fieldPath?: string;
  details?: Record<string, any>;
}





// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  primaryKey?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: Record<string, any>; // Metadata field selection

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...config.headers,
    ...processedConfig.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...config.fetchOptions,
    ...processedConfig.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network",
          message: response.statusText,
          details: {}
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...config.headers,
    ...processedConfig.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...config.fetchOptions,
    ...processedConfig.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network",
          message: response.statusText,
          details: {}
        }
      ],
    } as T;
  }

  return result as T;
}









export type GetOrganizationsFields = UnifiedFieldSelection<OrganizationResourceSchema>[];


type InferGetOrganizationsResult<
  Fields extends GetOrganizationsFields | undefined,
  Page extends GetOrganizationsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<OrganizationResourceSchema, Fields>>, {
  results: Array<InferResult<OrganizationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<OrganizationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetOrganizationsConfig = {
  fields: GetOrganizationsFields;
  filter?: OrganizationFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetOrganizationsResult<Fields extends GetOrganizationsFields, Page extends GetOrganizationsConfig["page"] = undefined> = | { success: true; data: InferGetOrganizationsResult<Fields, Page>; }
| {
        success: false;
        errors: Array<{
          type: string;
          message: string;
          fieldPath?: string;
          details: Record<string, string>;
        }>;
      }

;

export async function getOrganizations<Fields extends GetOrganizationsFields, Config extends GetOrganizationsConfig = GetOrganizationsConfig>(
  config: Config & { fields: Fields }
): Promise<GetOrganizationsResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_organizations",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetOrganizationsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type ValidateGetOrganizationsResult =
  | { success: true }
  | {
      success: false;
      errors: Array<{
        type: string;
        message: string;
        field?: string;
        fieldPath?: string;
        details?: Record<string, any>;
      }>;
    };


export async function validateGetOrganizations(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidateGetOrganizationsResult> {
  const payload = {
    action: "get_organizations"
  };

  return executeValidationRpcRequest<ValidateGetOrganizationsResult>(
    payload,
    config
  );
}


export type GetUsersFields = UnifiedFieldSelection<UserResourceSchema>[];


type InferGetUsersResult<
  Fields extends GetUsersFields | undefined,
  Page extends GetUsersConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<UserResourceSchema, Fields>>, {
  results: Array<InferResult<UserResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<UserResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetUsersConfig = {
  fields: GetUsersFields;
  filter?: UserFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetUsersResult<Fields extends GetUsersFields, Page extends GetUsersConfig["page"] = undefined> = | { success: true; data: InferGetUsersResult<Fields, Page>; }
| {
        success: false;
        errors: Array<{
          type: string;
          message: string;
          fieldPath?: string;
          details: Record<string, string>;
        }>;
      }

;

export async function getUsers<Fields extends GetUsersFields, Config extends GetUsersConfig = GetUsersConfig>(
  config: Config & { fields: Fields }
): Promise<GetUsersResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_users",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetUsersResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type ValidateGetUsersResult =
  | { success: true }
  | {
      success: false;
      errors: Array<{
        type: string;
        message: string;
        field?: string;
        fieldPath?: string;
        details?: Record<string, any>;
      }>;
    };


export async function validateGetUsers(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidateGetUsersResult> {
  const payload = {
    action: "get_users"
  };

  return executeValidationRpcRequest<ValidateGetUsersResult>(
    payload,
    config
  );
}


export type GetPreferencesFields = UnifiedFieldSelection<PreferenceResourceSchema>[];


type InferGetPreferencesResult<
  Fields extends GetPreferencesFields | undefined,
  Page extends GetPreferencesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<PreferenceResourceSchema, Fields>>, {
  results: Array<InferResult<PreferenceResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<PreferenceResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetPreferencesConfig = {
  fields: GetPreferencesFields;
  filter?: PreferenceFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetPreferencesResult<Fields extends GetPreferencesFields, Page extends GetPreferencesConfig["page"] = undefined> = | { success: true; data: InferGetPreferencesResult<Fields, Page>; }
| {
        success: false;
        errors: Array<{
          type: string;
          message: string;
          fieldPath?: string;
          details: Record<string, string>;
        }>;
      }

;

export async function getPreferences<Fields extends GetPreferencesFields, Config extends GetPreferencesConfig = GetPreferencesConfig>(
  config: Config & { fields: Fields }
): Promise<GetPreferencesResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_preferences",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetPreferencesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type ValidateGetPreferencesResult =
  | { success: true }
  | {
      success: false;
      errors: Array<{
        type: string;
        message: string;
        field?: string;
        fieldPath?: string;
        details?: Record<string, any>;
      }>;
    };


export async function validateGetPreferences(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidateGetPreferencesResult> {
  const payload = {
    action: "get_preferences"
  };

  return executeValidationRpcRequest<ValidateGetPreferencesResult>(
    payload,
    config
  );
}


export type ListPetitionsFields = UnifiedFieldSelection<PetitionResourceSchema>[];


type InferListPetitionsResult<
  Fields extends ListPetitionsFields | undefined,
  Page extends ListPetitionsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<PetitionResourceSchema, Fields>>, {
  results: Array<InferResult<PetitionResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<PetitionResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListPetitionsConfig = {
  fields: ListPetitionsFields;
  filter?: PetitionFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListPetitionsResult<Fields extends ListPetitionsFields, Page extends ListPetitionsConfig["page"] = undefined> = | { success: true; data: InferListPetitionsResult<Fields, Page>; }
| {
        success: false;
        errors: Array<{
          type: string;
          message: string;
          fieldPath?: string;
          details: Record<string, string>;
        }>;
      }

;

export async function listPetitions<Fields extends ListPetitionsFields, Config extends ListPetitionsConfig = ListPetitionsConfig>(
  config: Config & { fields: Fields }
): Promise<ListPetitionsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_petitions",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListPetitionsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type ValidateListPetitionsResult =
  | { success: true }
  | {
      success: false;
      errors: Array<{
        type: string;
        message: string;
        field?: string;
        fieldPath?: string;
        details?: Record<string, any>;
      }>;
    };


export async function validateListPetitions(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidateListPetitionsResult> {
  const payload = {
    action: "list_petitions"
  };

  return executeValidationRpcRequest<ValidateListPetitionsResult>(
    payload,
    config
  );
}


export type CreatePetitionInput = {
  title?: string | null;
  description?: string | null;
  status?: string | null;
};

export type CreatePetitionValidationErrors = {
  title?: string[];
  description?: string[];
  status?: string[];
};

export type CreatePetitionFields = UnifiedFieldSelection<PetitionResourceSchema>[];

type InferCreatePetitionResult<
  Fields extends CreatePetitionFields | undefined,
> = InferResult<PetitionResourceSchema, Fields>;

export type CreatePetitionResult<Fields extends CreatePetitionFields | undefined = undefined> = | { success: true; data: InferCreatePetitionResult<Fields>; }
| {
        success: false;
        errors: Array<{
          type: string;
          message: string;
          fieldPath?: string;
          details: Record<string, string>;
        }>;
      }

;

export async function createPetition<Fields extends CreatePetitionFields | undefined = undefined>(
  config: {
  input: CreatePetitionInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreatePetitionResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_petition",
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreatePetitionResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


export type ValidateCreatePetitionResult =
  | { success: true }
  | {
      success: false;
      errors: Array<{
        type: string;
        message: string;
        field?: string;
        fieldPath?: string;
        details?: Record<string, any>;
      }>;
    };


export async function validateCreatePetition(
  config: {
  input: CreatePetitionInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidateCreatePetitionResult> {
  const payload = {
    action: "create_petition",
    input: config.input
  };

  return executeValidationRpcRequest<ValidateCreatePetitionResult>(
    payload,
    config
  );
}


export type ListCommentsFields = UnifiedFieldSelection<CommentResourceSchema>[];


type InferListCommentsResult<
  Fields extends ListCommentsFields | undefined,
  Page extends ListCommentsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<CommentResourceSchema, Fields>>, {
  results: Array<InferResult<CommentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<CommentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListCommentsConfig = {
  fields: ListCommentsFields;
  filter?: CommentFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListCommentsResult<Fields extends ListCommentsFields, Page extends ListCommentsConfig["page"] = undefined> = | { success: true; data: InferListCommentsResult<Fields, Page>; }
| {
        success: false;
        errors: Array<{
          type: string;
          message: string;
          fieldPath?: string;
          details: Record<string, string>;
        }>;
      }

;

export async function listComments<Fields extends ListCommentsFields, Config extends ListCommentsConfig = ListCommentsConfig>(
  config: Config & { fields: Fields }
): Promise<ListCommentsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_comments",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListCommentsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type ValidateListCommentsResult =
  | { success: true }
  | {
      success: false;
      errors: Array<{
        type: string;
        message: string;
        field?: string;
        fieldPath?: string;
        details?: Record<string, any>;
      }>;
    };


export async function validateListComments(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidateListCommentsResult> {
  const payload = {
    action: "list_comments"
  };

  return executeValidationRpcRequest<ValidateListCommentsResult>(
    payload,
    config
  );
}


export type CreateCommentFields = UnifiedFieldSelection<CommentResourceSchema>[];

type InferCreateCommentResult<
  Fields extends CreateCommentFields | undefined,
> = InferResult<CommentResourceSchema, Fields>;

export type CreateCommentResult<Fields extends CreateCommentFields | undefined = undefined> = | { success: true; data: InferCreateCommentResult<Fields>; }
| {
        success: false;
        errors: Array<{
          type: string;
          message: string;
          fieldPath?: string;
          details: Record<string, string>;
        }>;
      }

;

export async function createComment<Fields extends CreateCommentFields | undefined = undefined>(
  config: {
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateCommentResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_comment",
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateCommentResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


export type ValidateCreateCommentResult =
  | { success: true }
  | {
      success: false;
      errors: Array<{
        type: string;
        message: string;
        field?: string;
        fieldPath?: string;
        details?: Record<string, any>;
      }>;
    };


export async function validateCreateComment(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidateCreateCommentResult> {
  const payload = {
    action: "create_comment"
  };

  return executeValidationRpcRequest<ValidateCreateCommentResult>(
    payload,
    config
  );
}


