// Generated by AshTypescript - RPC Actions
// Do not edit this file manually


import type { AshRpcError, CategoryFilterInput, CategoryResourceSchema, CategorySortField, ClassroomFilterInput, ClassroomMembershipFilterInput, ClassroomMembershipResourceSchema, ClassroomMembershipSortField, ClassroomResourceSchema, ClassroomSortField, CommentFilterInput, CommentResourceSchema, CommentSortField, ConditionalPaginatedResultMixed, InferResult, NotificationFilterInput, NotificationResourceSchema, NotificationSortField, OrganizationFilterInput, OrganizationResourceSchema, OrganizationSortField, PetitionFilterInput, PetitionResourceSchema, PetitionSortField, PreferenceFilterInput, PreferenceResourceSchema, PreferenceSortField, SignatureFilterInput, SignatureResourceSchema, SignatureSortField, SortString, UUID, UUIDv7, UnifiedFieldSelection, UpdateFilterInput, UpdateResourceSchema, UpdateSortField, UserFilterInput, UserResourceSchema, UserSortField, UtcDateTime, ValidationResult } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string | string[]; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
export async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}







export type GetNotificationsFields = UnifiedFieldSelection<NotificationResourceSchema>[];


export type InferGetNotificationsResult<
  Fields extends GetNotificationsFields | undefined,
  Page extends GetNotificationsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<NotificationResourceSchema, Fields>>, {
  results: Array<InferResult<NotificationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<NotificationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetNotificationsConfig = {
  tenant?: string;
  fields: GetNotificationsFields;
  filter?: NotificationFilterInput;
  sort?: SortString<NotificationSortField> | SortString<NotificationSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetNotificationsResult<Fields extends GetNotificationsFields, Page extends GetNotificationsConfig["page"] = undefined> = | { success: true; data: InferGetNotificationsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Notification records
 *
 * @ashActionType :read
 */
export async function getNotifications<Fields extends GetNotificationsFields, Config extends GetNotificationsConfig = GetNotificationsConfig>(
  config: Config & { fields: Fields }
): Promise<GetNotificationsResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_notifications",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetNotificationsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Notification records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetNotifications(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_notifications",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetOrganizationsFields = UnifiedFieldSelection<OrganizationResourceSchema>[];


export type InferGetOrganizationsResult<
  Fields extends GetOrganizationsFields | undefined,
  Page extends GetOrganizationsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<OrganizationResourceSchema, Fields>>, {
  results: Array<InferResult<OrganizationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<OrganizationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetOrganizationsConfig = {
  tenant?: string;
  fields: GetOrganizationsFields;
  filter?: OrganizationFilterInput;
  sort?: SortString<OrganizationSortField> | SortString<OrganizationSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetOrganizationsResult<Fields extends GetOrganizationsFields, Page extends GetOrganizationsConfig["page"] = undefined> = | { success: true; data: InferGetOrganizationsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Organization records
 *
 * @ashActionType :read
 */
export async function getOrganizations<Fields extends GetOrganizationsFields, Config extends GetOrganizationsConfig = GetOrganizationsConfig>(
  config: Config & { fields: Fields }
): Promise<GetOrganizationsResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_organizations",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetOrganizationsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Organization records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetOrganizations(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_organizations",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetPreferencesFields = UnifiedFieldSelection<PreferenceResourceSchema>[];


export type InferGetPreferencesResult<
  Fields extends GetPreferencesFields | undefined,
  Page extends GetPreferencesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<PreferenceResourceSchema, Fields>>, {
  results: Array<InferResult<PreferenceResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<PreferenceResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetPreferencesConfig = {
  tenant?: string;
  fields: GetPreferencesFields;
  filter?: PreferenceFilterInput;
  sort?: SortString<PreferenceSortField> | SortString<PreferenceSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetPreferencesResult<Fields extends GetPreferencesFields, Page extends GetPreferencesConfig["page"] = undefined> = | { success: true; data: InferGetPreferencesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Preference records
 *
 * @ashActionType :read
 */
export async function getPreferences<Fields extends GetPreferencesFields, Config extends GetPreferencesConfig = GetPreferencesConfig>(
  config: Config & { fields: Fields }
): Promise<GetPreferencesResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_preferences",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetPreferencesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Preference records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetPreferences(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_preferences",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetMeFields = UnifiedFieldSelection<UserResourceSchema>[];
export type InferGetMeResult<
  Fields extends GetMeFields,
> = InferResult<UserResourceSchema, Fields>;

export type GetMeResult<Fields extends GetMeFields> = | { success: true; data: InferGetMeResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function getMe<Fields extends GetMeFields>(
  config: {
  tenant?: string;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetMeResult<Fields>> {
  const payload = {
    action: "get_me",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetMeResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetMe(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_me",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetUserByIdInput = {
  id: UUID;
  includeStats?: boolean | null;
};

export type GetUserByIdFields = UnifiedFieldSelection<UserResourceSchema>[];
export type InferGetUserByIdResult<
  Fields extends GetUserByIdFields,
> = InferResult<UserResourceSchema, Fields>;

export type GetUserByIdResult<Fields extends GetUserByIdFields> = | { success: true; data: InferGetUserByIdResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function getUserById<Fields extends GetUserByIdFields>(
  config: {
  tenant?: string;
  input: GetUserByIdInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetUserByIdResult<Fields>> {
  const payload = {
    action: "get_user_by_id",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetUserByIdResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetUserById(
  config: {
  tenant?: string;
  input: GetUserByIdInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_user_by_id",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetUsersFields = UnifiedFieldSelection<UserResourceSchema>[];
export type InferGetUsersResult<
  Fields extends GetUsersFields,
> = Array<InferResult<UserResourceSchema, Fields>>;

export type GetUsersResult<Fields extends GetUsersFields> = | { success: true; data: InferGetUsersResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function getUsers<Fields extends GetUsersFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: UserFilterInput;
  sort?: SortString<UserSortField> | SortString<UserSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetUsersResult<Fields>> {
  const payload = {
    action: "get_users",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<GetUsersResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetUsers(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_users",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type SetUserRoleInput = {
  role?: "admin" | "professor" | "student" | "superadmin";
};

export type SetUserRoleFields = UnifiedFieldSelection<UserResourceSchema>[];

export type InferSetUserRoleResult<
  Fields extends SetUserRoleFields | undefined,
> = InferResult<UserResourceSchema, Fields>;

export type SetUserRoleResult<Fields extends SetUserRoleFields | undefined = undefined> = | { success: true; data: InferSetUserRoleResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing User
 *
 * @ashActionType :update
 */
export async function setUserRole<Fields extends SetUserRoleFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input?: SetUserRoleInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SetUserRoleResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "set_user_role",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SetUserRoleResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing User
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateSetUserRole(
  config: {
  tenant?: string;
  identity: UUID | string;
  input?: SetUserRoleInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "set_user_role",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetCategoriesFields = UnifiedFieldSelection<CategoryResourceSchema>[];


export type InferGetCategoriesResult<
  Fields extends GetCategoriesFields | undefined,
  Page extends GetCategoriesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<CategoryResourceSchema, Fields>>, {
  results: Array<InferResult<CategoryResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<CategoryResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetCategoriesConfig = {
  tenant?: string;
  fields: GetCategoriesFields;
  filter?: CategoryFilterInput;
  sort?: SortString<CategorySortField> | SortString<CategorySortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetCategoriesResult<Fields extends GetCategoriesFields, Page extends GetCategoriesConfig["page"] = undefined> = | { success: true; data: InferGetCategoriesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Category records
 *
 * @ashActionType :read
 */
export async function getCategories<Fields extends GetCategoriesFields, Config extends GetCategoriesConfig = GetCategoriesConfig>(
  config: Config & { fields: Fields }
): Promise<GetCategoriesResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_categories",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetCategoriesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Category records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetCategories(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_categories",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ArchiveClassroomFields = UnifiedFieldSelection<ClassroomResourceSchema>[];

export type InferArchiveClassroomResult<
  Fields extends ArchiveClassroomFields | undefined,
> = InferResult<ClassroomResourceSchema, Fields>;

export type ArchiveClassroomResult<Fields extends ArchiveClassroomFields | undefined = undefined> = | { success: true; data: InferArchiveClassroomResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Classroom
 *
 * @ashActionType :update
 */
export async function archiveClassroom<Fields extends ArchiveClassroomFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ArchiveClassroomResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "archive_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ArchiveClassroomResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Classroom
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateArchiveClassroom(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "archive_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateClassroomInput = {
  name: string;
  description?: string | null;
  allowStudentPetitions?: boolean;
  organizationId?: UUID | null;
};

export type CreateClassroomFields = UnifiedFieldSelection<ClassroomResourceSchema>[];

export type InferCreateClassroomResult<
  Fields extends CreateClassroomFields | undefined,
> = InferResult<ClassroomResourceSchema, Fields>;

export type CreateClassroomResult<Fields extends CreateClassroomFields | undefined = undefined> = | { success: true; data: InferCreateClassroomResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Classroom
 *
 * @ashActionType :create
 */
export async function createClassroom<Fields extends CreateClassroomFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateClassroomInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateClassroomResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateClassroomResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Classroom
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateClassroom(
  config: {
  tenant?: string;
  input: CreateClassroomInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetClassroomByIdInput = {
  id: UUIDv7;
};

export type GetClassroomByIdFields = UnifiedFieldSelection<ClassroomResourceSchema>[];
export type InferGetClassroomByIdResult<
  Fields extends GetClassroomByIdFields,
> = InferResult<ClassroomResourceSchema, Fields>;

export type GetClassroomByIdResult<Fields extends GetClassroomByIdFields> = | { success: true; data: InferGetClassroomByIdResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Classroom records
 *
 * @ashActionType :read
 */
export async function getClassroomById<Fields extends GetClassroomByIdFields>(
  config: {
  tenant?: string;
  input: GetClassroomByIdInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetClassroomByIdResult<Fields>> {
  const payload = {
    action: "get_classroom_by_id",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetClassroomByIdResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Classroom records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetClassroomById(
  config: {
  tenant?: string;
  input: GetClassroomByIdInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_classroom_by_id",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetClassroomsFields = UnifiedFieldSelection<ClassroomResourceSchema>[];


export type InferGetClassroomsResult<
  Fields extends GetClassroomsFields | undefined,
  Page extends GetClassroomsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<ClassroomResourceSchema, Fields>>, {
  results: Array<InferResult<ClassroomResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<ClassroomResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetClassroomsConfig = {
  tenant?: string;
  fields: GetClassroomsFields;
  filter?: ClassroomFilterInput;
  sort?: SortString<ClassroomSortField> | SortString<ClassroomSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetClassroomsResult<Fields extends GetClassroomsFields, Page extends GetClassroomsConfig["page"] = undefined> = | { success: true; data: InferGetClassroomsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Classroom records
 *
 * @ashActionType :read
 */
export async function getClassrooms<Fields extends GetClassroomsFields, Config extends GetClassroomsConfig = GetClassroomsConfig>(
  config: Config & { fields: Fields }
): Promise<GetClassroomsResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_classrooms",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetClassroomsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Classroom records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetClassrooms(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_classrooms",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetMyClassroomsFields = UnifiedFieldSelection<ClassroomResourceSchema>[];
export type InferGetMyClassroomsResult<
  Fields extends GetMyClassroomsFields,
> = Array<InferResult<ClassroomResourceSchema, Fields>>;

export type GetMyClassroomsResult<Fields extends GetMyClassroomsFields> = | { success: true; data: InferGetMyClassroomsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Classroom records
 *
 * @ashActionType :read
 */
export async function getMyClassrooms<Fields extends GetMyClassroomsFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: ClassroomFilterInput;
  sort?: SortString<ClassroomSortField> | SortString<ClassroomSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetMyClassroomsResult<Fields>> {
  const payload = {
    action: "get_my_classrooms",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<GetMyClassroomsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Classroom records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetMyClassrooms(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_my_classrooms",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RegenerateJoinCodeFields = UnifiedFieldSelection<ClassroomResourceSchema>[];

export type InferRegenerateJoinCodeResult<
  Fields extends RegenerateJoinCodeFields | undefined,
> = InferResult<ClassroomResourceSchema, Fields>;

export type RegenerateJoinCodeResult<Fields extends RegenerateJoinCodeFields | undefined = undefined> = | { success: true; data: InferRegenerateJoinCodeResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Classroom
 *
 * @ashActionType :update
 */
export async function regenerateJoinCode<Fields extends RegenerateJoinCodeFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RegenerateJoinCodeResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "regenerate_join_code",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RegenerateJoinCodeResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Classroom
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateRegenerateJoinCode(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "regenerate_join_code",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UnarchiveClassroomFields = UnifiedFieldSelection<ClassroomResourceSchema>[];

export type InferUnarchiveClassroomResult<
  Fields extends UnarchiveClassroomFields | undefined,
> = InferResult<ClassroomResourceSchema, Fields>;

export type UnarchiveClassroomResult<Fields extends UnarchiveClassroomFields | undefined = undefined> = | { success: true; data: InferUnarchiveClassroomResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Classroom
 *
 * @ashActionType :update
 */
export async function unarchiveClassroom<Fields extends UnarchiveClassroomFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UnarchiveClassroomResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "unarchive_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UnarchiveClassroomResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Classroom
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUnarchiveClassroom(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "unarchive_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type UpdateClassroomInput = {
  name?: string;
  description?: string | null;
  allowStudentPetitions?: boolean;
};

export type UpdateClassroomFields = UnifiedFieldSelection<ClassroomResourceSchema>[];

export type InferUpdateClassroomResult<
  Fields extends UpdateClassroomFields | undefined,
> = InferResult<ClassroomResourceSchema, Fields>;

export type UpdateClassroomResult<Fields extends UpdateClassroomFields | undefined = undefined> = | { success: true; data: InferUpdateClassroomResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Classroom
 *
 * @ashActionType :update
 */
export async function updateClassroom<Fields extends UpdateClassroomFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  input: UpdateClassroomInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateClassroomResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateClassroomResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing Classroom
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateUpdateClassroom(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  input: UpdateClassroomInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "update_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ApproveMembershipFields = UnifiedFieldSelection<ClassroomMembershipResourceSchema>[];

export type InferApproveMembershipResult<
  Fields extends ApproveMembershipFields | undefined,
> = InferResult<ClassroomMembershipResourceSchema, Fields>;

export type ApproveMembershipResult<Fields extends ApproveMembershipFields | undefined = undefined> = | { success: true; data: InferApproveMembershipResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing ClassroomMembership
 *
 * @ashActionType :update
 */
export async function approveMembership<Fields extends ApproveMembershipFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ApproveMembershipResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "approve_membership",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<ApproveMembershipResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing ClassroomMembership
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateApproveMembership(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "approve_membership",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type DemoteToStudentFields = UnifiedFieldSelection<ClassroomMembershipResourceSchema>[];

export type InferDemoteToStudentResult<
  Fields extends DemoteToStudentFields | undefined,
> = InferResult<ClassroomMembershipResourceSchema, Fields>;

export type DemoteToStudentResult<Fields extends DemoteToStudentFields | undefined = undefined> = | { success: true; data: InferDemoteToStudentResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing ClassroomMembership
 *
 * @ashActionType :update
 */
export async function demoteToStudent<Fields extends DemoteToStudentFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DemoteToStudentResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "demote_to_student",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<DemoteToStudentResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing ClassroomMembership
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateDemoteToStudent(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "demote_to_student",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetClassroomMembershipsFields = UnifiedFieldSelection<ClassroomMembershipResourceSchema>[];


export type InferGetClassroomMembershipsResult<
  Fields extends GetClassroomMembershipsFields | undefined,
  Page extends GetClassroomMembershipsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<ClassroomMembershipResourceSchema, Fields>>, {
  results: Array<InferResult<ClassroomMembershipResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<ClassroomMembershipResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetClassroomMembershipsConfig = {
  tenant?: string;
  fields: GetClassroomMembershipsFields;
  filter?: ClassroomMembershipFilterInput;
  sort?: SortString<ClassroomMembershipSortField> | SortString<ClassroomMembershipSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetClassroomMembershipsResult<Fields extends GetClassroomMembershipsFields, Page extends GetClassroomMembershipsConfig["page"] = undefined> = | { success: true; data: InferGetClassroomMembershipsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read ClassroomMembership records
 *
 * @ashActionType :read
 */
export async function getClassroomMemberships<Fields extends GetClassroomMembershipsFields, Config extends GetClassroomMembershipsConfig = GetClassroomMembershipsConfig>(
  config: Config & { fields: Fields }
): Promise<GetClassroomMembershipsResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_classroom_memberships",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetClassroomMembershipsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read ClassroomMembership records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetClassroomMemberships(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_classroom_memberships",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetMembershipsForClassroomInput = {
  classroomId: UUID;
};

export type GetMembershipsForClassroomFields = UnifiedFieldSelection<ClassroomMembershipResourceSchema>[];
export type InferGetMembershipsForClassroomResult<
  Fields extends GetMembershipsForClassroomFields,
> = Array<InferResult<ClassroomMembershipResourceSchema, Fields>>;

export type GetMembershipsForClassroomResult<Fields extends GetMembershipsForClassroomFields> = | { success: true; data: InferGetMembershipsForClassroomResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read ClassroomMembership records
 *
 * @ashActionType :read
 */
export async function getMembershipsForClassroom<Fields extends GetMembershipsForClassroomFields>(
  config: {
  tenant?: string;
  input: GetMembershipsForClassroomInput;
  fields: Fields;
  filter?: ClassroomMembershipFilterInput;
  sort?: SortString<ClassroomMembershipSortField> | SortString<ClassroomMembershipSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetMembershipsForClassroomResult<Fields>> {
  const payload = {
    action: "get_memberships_for_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<GetMembershipsForClassroomResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read ClassroomMembership records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetMembershipsForClassroom(
  config: {
  tenant?: string;
  input: GetMembershipsForClassroomInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_memberships_for_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetPendingMembershipsInput = {
  classroomId: UUID;
};

export type GetPendingMembershipsFields = UnifiedFieldSelection<ClassroomMembershipResourceSchema>[];
export type InferGetPendingMembershipsResult<
  Fields extends GetPendingMembershipsFields,
> = Array<InferResult<ClassroomMembershipResourceSchema, Fields>>;

export type GetPendingMembershipsResult<Fields extends GetPendingMembershipsFields> = | { success: true; data: InferGetPendingMembershipsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read ClassroomMembership records
 *
 * @ashActionType :read
 */
export async function getPendingMemberships<Fields extends GetPendingMembershipsFields>(
  config: {
  tenant?: string;
  input: GetPendingMembershipsInput;
  fields: Fields;
  filter?: ClassroomMembershipFilterInput;
  sort?: SortString<ClassroomMembershipSortField> | SortString<ClassroomMembershipSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetPendingMembershipsResult<Fields>> {
  const payload = {
    action: "get_pending_memberships",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<GetPendingMembershipsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read ClassroomMembership records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetPendingMemberships(
  config: {
  tenant?: string;
  input: GetPendingMembershipsInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_pending_memberships",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type InviteToClassroomInput = {
  classroomId: UUID;
  email: string;
  role?: "student" | "ta" | null;
};

export type InviteToClassroomFields = UnifiedFieldSelection<ClassroomMembershipResourceSchema>[];

export type InferInviteToClassroomResult<
  Fields extends InviteToClassroomFields | undefined,
> = InferResult<ClassroomMembershipResourceSchema, Fields>;

export type InviteToClassroomResult<Fields extends InviteToClassroomFields | undefined = undefined> = | { success: true; data: InferInviteToClassroomResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new ClassroomMembership
 *
 * @ashActionType :create
 */
export async function inviteToClassroom<Fields extends InviteToClassroomFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: InviteToClassroomInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<InviteToClassroomResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "invite_to_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<InviteToClassroomResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new ClassroomMembership
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateInviteToClassroom(
  config: {
  tenant?: string;
  input: InviteToClassroomInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "invite_to_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type JoinClassroomByCodeInput = {
  joinCode: UUID;
};

export type JoinClassroomByCodeFields = UnifiedFieldSelection<ClassroomMembershipResourceSchema>[];

export type InferJoinClassroomByCodeResult<
  Fields extends JoinClassroomByCodeFields | undefined,
> = InferResult<ClassroomMembershipResourceSchema, Fields>;

export type JoinClassroomByCodeResult<Fields extends JoinClassroomByCodeFields | undefined = undefined> = | { success: true; data: InferJoinClassroomByCodeResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new ClassroomMembership
 *
 * @ashActionType :create
 */
export async function joinClassroomByCode<Fields extends JoinClassroomByCodeFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: JoinClassroomByCodeInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<JoinClassroomByCodeResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "join_classroom_by_code",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<JoinClassroomByCodeResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new ClassroomMembership
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateJoinClassroomByCode(
  config: {
  tenant?: string;
  input: JoinClassroomByCodeInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "join_classroom_by_code",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type PromoteToTaFields = UnifiedFieldSelection<ClassroomMembershipResourceSchema>[];

export type InferPromoteToTaResult<
  Fields extends PromoteToTaFields | undefined,
> = InferResult<ClassroomMembershipResourceSchema, Fields>;

export type PromoteToTaResult<Fields extends PromoteToTaFields | undefined = undefined> = | { success: true; data: InferPromoteToTaResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing ClassroomMembership
 *
 * @ashActionType :update
 */
export async function promoteToTa<Fields extends PromoteToTaFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<PromoteToTaResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "promote_to_ta",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<PromoteToTaResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing ClassroomMembership
 *
 * @ashActionType :update
 * @validation true
 */
export async function validatePromoteToTa(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "promote_to_ta",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RemoveFromClassroomFields = UnifiedFieldSelection<ClassroomMembershipResourceSchema>[];

export type InferRemoveFromClassroomResult<
  Fields extends RemoveFromClassroomFields | undefined,
> = InferResult<ClassroomMembershipResourceSchema, Fields>;

export type RemoveFromClassroomResult<Fields extends RemoveFromClassroomFields | undefined = undefined> = | { success: true; data: InferRemoveFromClassroomResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing ClassroomMembership
 *
 * @ashActionType :update
 */
export async function removeFromClassroom<Fields extends RemoveFromClassroomFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUIDv7;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RemoveFromClassroomResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "remove_from_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RemoveFromClassroomResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing ClassroomMembership
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateRemoveFromClassroom(
  config: {
  tenant?: string;
  identity: UUIDv7 | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "remove_from_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type RequestToJoinClassroomInput = {
  classroomId: UUID;
};

export type RequestToJoinClassroomFields = UnifiedFieldSelection<ClassroomMembershipResourceSchema>[];

export type InferRequestToJoinClassroomResult<
  Fields extends RequestToJoinClassroomFields | undefined,
> = InferResult<ClassroomMembershipResourceSchema, Fields>;

export type RequestToJoinClassroomResult<Fields extends RequestToJoinClassroomFields | undefined = undefined> = | { success: true; data: InferRequestToJoinClassroomResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new ClassroomMembership
 *
 * @ashActionType :create
 */
export async function requestToJoinClassroom<Fields extends RequestToJoinClassroomFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: RequestToJoinClassroomInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<RequestToJoinClassroomResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "request_to_join_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<RequestToJoinClassroomResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new ClassroomMembership
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateRequestToJoinClassroom(
  config: {
  tenant?: string;
  input: RequestToJoinClassroomInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "request_to_join_classroom",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateCommentInput = {
  text?: string | null;
  parentCommentId?: UUIDv7 | null;
  petitionId: UUIDv7;
};

export type CreateCommentFields = UnifiedFieldSelection<CommentResourceSchema>[];

export type InferCreateCommentResult<
  Fields extends CreateCommentFields | undefined,
> = InferResult<CommentResourceSchema, Fields>;

export type CreateCommentResult<Fields extends CreateCommentFields | undefined = undefined> = | { success: true; data: InferCreateCommentResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Comment
 *
 * @ashActionType :create
 */
export async function createComment<Fields extends CreateCommentFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateCommentInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateCommentResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_comment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateCommentResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Comment
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateComment(
  config: {
  tenant?: string;
  input: CreateCommentInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_comment",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetCommentsFields = UnifiedFieldSelection<CommentResourceSchema>[];


export type InferGetCommentsResult<
  Fields extends GetCommentsFields | undefined,
  Page extends GetCommentsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<CommentResourceSchema, Fields>>, {
  results: Array<InferResult<CommentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<CommentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetCommentsConfig = {
  tenant?: string;
  fields: GetCommentsFields;
  filter?: CommentFilterInput;
  sort?: SortString<CommentSortField> | SortString<CommentSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetCommentsResult<Fields extends GetCommentsFields, Page extends GetCommentsConfig["page"] = undefined> = | { success: true; data: InferGetCommentsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Comment records
 *
 * @ashActionType :read
 */
export async function getComments<Fields extends GetCommentsFields, Config extends GetCommentsConfig = GetCommentsConfig>(
  config: Config & { fields: Fields }
): Promise<GetCommentsResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_comments",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetCommentsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Comment records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetComments(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_comments",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateClassroomPetitionInput = {
  title?: string | null;
  description?: string | null;
  status?: "closed" | "open" | "victory" | null;
  goal?: number | null;
  deadline?: UtcDateTime | null;
  allowComments?: boolean | null;
  isAnonymous?: boolean | null;
  categoryId: UUIDv7;
  classroomId: UUIDv7;
};

export type CreateClassroomPetitionFields = UnifiedFieldSelection<PetitionResourceSchema>[];

export type InferCreateClassroomPetitionResult<
  Fields extends CreateClassroomPetitionFields | undefined,
> = InferResult<PetitionResourceSchema, Fields>;

export type CreateClassroomPetitionResult<Fields extends CreateClassroomPetitionFields | undefined = undefined> = | { success: true; data: InferCreateClassroomPetitionResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Petition
 *
 * @ashActionType :create
 */
export async function createClassroomPetition<Fields extends CreateClassroomPetitionFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateClassroomPetitionInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateClassroomPetitionResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_classroom_petition",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateClassroomPetitionResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Petition
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateClassroomPetition(
  config: {
  tenant?: string;
  input: CreateClassroomPetitionInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_classroom_petition",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreatePetitionInput = {
  title?: string | null;
  description?: string | null;
  status?: "closed" | "open" | "victory" | null;
  goal?: number | null;
  deadline?: UtcDateTime | null;
  allowComments?: boolean | null;
  isAnonymous?: boolean | null;
  categoryId: UUIDv7;
};

export type CreatePetitionFields = UnifiedFieldSelection<PetitionResourceSchema>[];

export type InferCreatePetitionResult<
  Fields extends CreatePetitionFields | undefined,
> = InferResult<PetitionResourceSchema, Fields>;

export type CreatePetitionResult<Fields extends CreatePetitionFields | undefined = undefined> = | { success: true; data: InferCreatePetitionResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Petition
 *
 * @ashActionType :create
 */
export async function createPetition<Fields extends CreatePetitionFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreatePetitionInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreatePetitionResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_petition",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreatePetitionResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Petition
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreatePetition(
  config: {
  tenant?: string;
  input: CreatePetitionInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_petition",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetClassroomPetitionsInput = {
  classroomId: UUIDv7;
};

export type GetClassroomPetitionsFields = UnifiedFieldSelection<PetitionResourceSchema>[];
export type InferGetClassroomPetitionsResult<
  Fields extends GetClassroomPetitionsFields,
> = Array<InferResult<PetitionResourceSchema, Fields>>;

export type GetClassroomPetitionsResult<Fields extends GetClassroomPetitionsFields> = | { success: true; data: InferGetClassroomPetitionsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Petition records
 *
 * @ashActionType :read
 */
export async function getClassroomPetitions<Fields extends GetClassroomPetitionsFields>(
  config: {
  tenant?: string;
  input: GetClassroomPetitionsInput;
  fields: Fields;
  filter?: PetitionFilterInput;
  sort?: SortString<PetitionSortField> | SortString<PetitionSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetClassroomPetitionsResult<Fields>> {
  const payload = {
    action: "get_classroom_petitions",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<GetClassroomPetitionsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Petition records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetClassroomPetitions(
  config: {
  tenant?: string;
  input: GetClassroomPetitionsInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_classroom_petitions",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetPetitionByIdInput = {
  id: UUIDv7;
};

export type GetPetitionByIdFields = UnifiedFieldSelection<PetitionResourceSchema>[];
export type InferGetPetitionByIdResult<
  Fields extends GetPetitionByIdFields,
> = InferResult<PetitionResourceSchema, Fields>;

export type GetPetitionByIdResult<Fields extends GetPetitionByIdFields> = | { success: true; data: InferGetPetitionByIdResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Petition records
 *
 * @ashActionType :read
 */
export async function getPetitionById<Fields extends GetPetitionByIdFields>(
  config: {
  tenant?: string;
  input: GetPetitionByIdInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetPetitionByIdResult<Fields>> {
  const payload = {
    action: "get_petition_by_id",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetPetitionByIdResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Petition records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetPetitionById(
  config: {
  tenant?: string;
  input: GetPetitionByIdInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_petition_by_id",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetPetitionsFields = UnifiedFieldSelection<PetitionResourceSchema>[];


export type InferGetPetitionsResult<
  Fields extends GetPetitionsFields | undefined,
  Page extends GetPetitionsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<PetitionResourceSchema, Fields>>, {
  results: Array<InferResult<PetitionResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<PetitionResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetPetitionsConfig = {
  tenant?: string;
  fields: GetPetitionsFields;
  filter?: PetitionFilterInput;
  sort?: SortString<PetitionSortField> | SortString<PetitionSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetPetitionsResult<Fields extends GetPetitionsFields, Page extends GetPetitionsConfig["page"] = undefined> = | { success: true; data: InferGetPetitionsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Petition records
 *
 * @ashActionType :read
 */
export async function getPetitions<Fields extends GetPetitionsFields, Config extends GetPetitionsConfig = GetPetitionsConfig>(
  config: Config & { fields: Fields }
): Promise<GetPetitionsResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_petitions",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetPetitionsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Petition records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetPetitions(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_petitions",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetPublicPetitionsFields = UnifiedFieldSelection<PetitionResourceSchema>[];
export type InferGetPublicPetitionsResult<
  Fields extends GetPublicPetitionsFields,
> = Array<InferResult<PetitionResourceSchema, Fields>>;

export type GetPublicPetitionsResult<Fields extends GetPublicPetitionsFields> = | { success: true; data: InferGetPublicPetitionsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Petition records
 *
 * @ashActionType :read
 */
export async function getPublicPetitions<Fields extends GetPublicPetitionsFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: PetitionFilterInput;
  sort?: SortString<PetitionSortField> | SortString<PetitionSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetPublicPetitionsResult<Fields>> {
  const payload = {
    action: "get_public_petitions",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<GetPublicPetitionsResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Petition records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetPublicPetitions(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_public_petitions",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateSignatureInput = {
  reason?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  isVerified?: boolean | null;
  petitionId: UUID;
  userId: UUID;
};

export type CreateSignatureFields = UnifiedFieldSelection<SignatureResourceSchema>[];

export type InferCreateSignatureResult<
  Fields extends CreateSignatureFields | undefined,
> = InferResult<SignatureResourceSchema, Fields>;

export type CreateSignatureResult<Fields extends CreateSignatureFields | undefined = undefined> = | { success: true; data: InferCreateSignatureResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Signature
 *
 * @ashActionType :create
 */
export async function createSignature<Fields extends CreateSignatureFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateSignatureInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateSignatureResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_signature",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateSignatureResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Signature
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateSignature(
  config: {
  tenant?: string;
  input: CreateSignatureInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_signature",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetSignaturesFields = UnifiedFieldSelection<SignatureResourceSchema>[];


export type InferGetSignaturesResult<
  Fields extends GetSignaturesFields | undefined,
  Page extends GetSignaturesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<SignatureResourceSchema, Fields>>, {
  results: Array<InferResult<SignatureResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<SignatureResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetSignaturesConfig = {
  tenant?: string;
  fields: GetSignaturesFields;
  filter?: SignatureFilterInput;
  sort?: SortString<SignatureSortField> | SortString<SignatureSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetSignaturesResult<Fields extends GetSignaturesFields, Page extends GetSignaturesConfig["page"] = undefined> = | { success: true; data: InferGetSignaturesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Signature records
 *
 * @ashActionType :read
 */
export async function getSignatures<Fields extends GetSignaturesFields, Config extends GetSignaturesConfig = GetSignaturesConfig>(
  config: Config & { fields: Fields }
): Promise<GetSignaturesResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_signatures",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetSignaturesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Signature records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetSignatures(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_signatures",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateUpdateInput = {
  title: string;
  body: string;
  petitionId?: UUID | null;
};

export type CreateUpdateFields = UnifiedFieldSelection<UpdateResourceSchema>[];

export type InferCreateUpdateResult<
  Fields extends CreateUpdateFields | undefined,
> = InferResult<UpdateResourceSchema, Fields>;

export type CreateUpdateResult<Fields extends CreateUpdateFields | undefined = undefined> = | { success: true; data: InferCreateUpdateResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Update
 *
 * @ashActionType :create
 */
export async function createUpdate<Fields extends CreateUpdateFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateUpdateInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateUpdateResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_update",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateUpdateResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Update
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateCreateUpdate(
  config: {
  tenant?: string;
  input: CreateUpdateInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_update",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetUpdatesFields = UnifiedFieldSelection<UpdateResourceSchema>[];


export type InferGetUpdatesResult<
  Fields extends GetUpdatesFields | undefined,
  Page extends GetUpdatesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<UpdateResourceSchema, Fields>>, {
  results: Array<InferResult<UpdateResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<UpdateResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetUpdatesConfig = {
  tenant?: string;
  fields: GetUpdatesFields;
  filter?: UpdateFilterInput;
  sort?: SortString<UpdateSortField> | SortString<UpdateSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetUpdatesResult<Fields extends GetUpdatesFields, Page extends GetUpdatesConfig["page"] = undefined> = | { success: true; data: InferGetUpdatesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Update records
 *
 * @ashActionType :read
 */
export async function getUpdates<Fields extends GetUpdatesFields, Config extends GetUpdatesConfig = GetUpdatesConfig>(
  config: Config & { fields: Fields }
): Promise<GetUpdatesResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_updates",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetUpdatesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Update records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetUpdates(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_updates",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetUpdatesForPetitionInput = {
  petitionId: UUIDv7;
};

export type GetUpdatesForPetitionFields = UnifiedFieldSelection<UpdateResourceSchema>[];
export type InferGetUpdatesForPetitionResult<
  Fields extends GetUpdatesForPetitionFields,
> = Array<InferResult<UpdateResourceSchema, Fields>>;

export type GetUpdatesForPetitionResult<Fields extends GetUpdatesForPetitionFields> = | { success: true; data: InferGetUpdatesForPetitionResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Update records
 *
 * @ashActionType :read
 */
export async function getUpdatesForPetition<Fields extends GetUpdatesForPetitionFields>(
  config: {
  tenant?: string;
  input: GetUpdatesForPetitionInput;
  fields: Fields;
  filter?: UpdateFilterInput;
  sort?: SortString<UpdateSortField> | SortString<UpdateSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetUpdatesForPetitionResult<Fields>> {
  const payload = {
    action: "get_updates_for_petition",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<GetUpdatesForPetitionResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read Update records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetUpdatesForPetition(
  config: {
  tenant?: string;
  input: GetUpdatesForPetitionInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_updates_for_petition",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}

