// Generated by AshTypescript - Shared Types
// Do not edit this file manually



export type UUID = string;
export type UUIDv7 = string;
export type UtcDateTime = string;
export type UtcDateTimeUsec = string;

// Notification Schema
export type NotificationResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "body" | "status" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  title: string;
  body: string | null;
  status: "archived" | "read" | "unread";
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



export type NotificationAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "body" | "status" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  title: string;
  body: string | null;
  status: "archived" | "read" | "unread";
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// Organization Schema
export type OrganizationResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "description" | "domain" | "logoUrl" | "allowPublicSignatures" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  name: string | null;
  description: string | null;
  domain: string | null;
  logoUrl: string | null;
  allowPublicSignatures: boolean | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



export type OrganizationAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "description" | "domain" | "logoUrl" | "allowPublicSignatures" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  name: string | null;
  description: string | null;
  domain: string | null;
  logoUrl: string | null;
  allowPublicSignatures: boolean | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// Preference Schema
export type PreferenceResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "value" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  name: string | null;
  value: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



export type PreferenceAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "value" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  name: string | null;
  value: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// User Schema
export type UserResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "firstName" | "lastName" | "email" | "graduationYear" | "role" | "insertedAt" | "updatedAt" | "numPetitions" | "numSigned" | "numPetitionSignees" | "totalPetitionSignatures";
  id: UUID;
  firstName: string | null;
  lastName: string | null;
  email: string;
  graduationYear: number | null;
  role: "admin" | "professor" | "student";
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  numPetitions: number;
  numSigned: number;
  numPetitionSignees: number;
  totalPetitionSignatures: number | null;
  petitions: { __type: "Relationship"; __array: true; __resource: PetitionResourceSchema; };
  signatures: { __type: "Relationship"; __array: true; __resource: SignatureResourceSchema; };
  classroomMemberships: { __type: "Relationship"; __array: true; __resource: ClassroomMembershipResourceSchema; };
  ownedClassrooms: { __type: "Relationship"; __array: true; __resource: ClassroomResourceSchema; };
};



export type UserAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "firstName" | "lastName" | "email" | "graduationYear" | "role" | "insertedAt" | "updatedAt";
  id: UUID;
  firstName: string | null;
  lastName: string | null;
  email: string;
  graduationYear: number | null;
  role: "admin" | "professor" | "student";
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// Category Schema
export type CategoryResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "description" | "color" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  name: string | null;
  description: string | null;
  color: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



export type CategoryAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "description" | "color" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  name: string | null;
  description: string | null;
  color: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// Classroom Schema
export type ClassroomResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "description" | "joinCode" | "archived" | "allowStudentPetitions" | "insertedAt" | "updatedAt" | "professorId" | "organizationId" | "memberCount" | "petitionCount";
  id: UUIDv7;
  name: string;
  description: string | null;
  joinCode: UUID;
  archived: boolean;
  allowStudentPetitions: boolean;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  professorId: UUID;
  organizationId: UUID | null;
  memberCount: number | null;
  petitionCount: number | null;
  professor: { __type: "Relationship"; __resource: UserResourceSchema; };
  organization: { __type: "Relationship"; __resource: OrganizationResourceSchema | null; };
  memberships: { __type: "Relationship"; __array: true; __resource: ClassroomMembershipResourceSchema; };
  petitions: { __type: "Relationship"; __array: true; __resource: PetitionResourceSchema; };
};



export type ClassroomAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "description" | "joinCode" | "archived" | "allowStudentPetitions" | "insertedAt" | "updatedAt" | "professorId" | "organizationId";
  id: UUIDv7;
  name: string;
  description: string | null;
  joinCode: UUID;
  archived: boolean;
  allowStudentPetitions: boolean;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  professorId: UUID;
  organizationId: UUID | null;
};


// ClassroomMembership Schema
export type ClassroomMembershipResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "role" | "status" | "joinedAt" | "insertedAt" | "updatedAt" | "classroomId" | "userId" | "invitedById";
  id: UUIDv7;
  role: "student" | "ta";
  status: "active" | "pending" | "removed";
  joinedAt: UtcDateTimeUsec | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  classroomId: UUID;
  userId: UUID;
  invitedById: UUID | null;
  classroom: { __type: "Relationship"; __resource: ClassroomResourceSchema; };
  user: { __type: "Relationship"; __resource: UserResourceSchema; };
  invitedBy: { __type: "Relationship"; __resource: UserResourceSchema | null; };
};



export type ClassroomMembershipAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "role" | "status" | "joinedAt" | "insertedAt" | "updatedAt" | "classroomId" | "userId" | "invitedById";
  id: UUIDv7;
  role: "student" | "ta";
  status: "active" | "pending" | "removed";
  joinedAt: UtcDateTimeUsec | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  classroomId: UUID;
  userId: UUID;
  invitedById: UUID | null;
};


// Comment Schema
export type CommentResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "text" | "sentiment" | "insertedAt" | "updatedAt" | "userId";
  id: UUIDv7;
  text: string | null;
  sentiment: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  userId: UUID | null;
  user: { __type: "Relationship"; __resource: UserResourceSchema | null; };
};



export type CommentAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "text" | "sentiment" | "insertedAt" | "updatedAt" | "userId";
  id: UUIDv7;
  text: string | null;
  sentiment: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  userId: UUID | null;
};


// Petition Schema
export type PetitionResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "description" | "status" | "goal" | "allowComments" | "isAnonymous" | "deadline" | "insertedAt" | "updatedAt" | "userId" | "categoryId" | "classroomId" | "signaturesCount" | "isClassroomPetition" | "daysLeft" | "author" | "trending";
  id: UUIDv7;
  title: string | null;
  description: string | null;
  status: "closed" | "open" | "victory" | null;
  goal: number | null;
  allowComments: boolean | null;
  isAnonymous: boolean | null;
  deadline: UtcDateTime | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  userId: UUID | null;
  categoryId: UUID | null;
  classroomId: UUID | null;
  signaturesCount: number | null;
  isClassroomPetition: boolean | null;
  daysLeft: number | null;
  author: string | null;
  trending: boolean | null;
  user: { __type: "Relationship"; __resource: UserResourceSchema | null; };
  category: { __type: "Relationship"; __resource: CategoryResourceSchema | null; };
  classroom: { __type: "Relationship"; __resource: ClassroomResourceSchema | null; };
  updates: { __type: "Relationship"; __array: true; __resource: UpdateResourceSchema; };
  comments: { __type: "Relationship"; __array: true; __resource: CommentResourceSchema; };
  signatures: { __type: "Relationship"; __array: true; __resource: SignatureResourceSchema; };
};



export type PetitionAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "description" | "status" | "goal" | "allowComments" | "isAnonymous" | "deadline" | "insertedAt" | "updatedAt" | "userId" | "categoryId" | "classroomId";
  id: UUIDv7;
  title: string | null;
  description: string | null;
  status: "closed" | "open" | "victory" | null;
  goal: number | null;
  allowComments: boolean | null;
  isAnonymous: boolean | null;
  deadline: UtcDateTime | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  userId: UUID | null;
  categoryId: UUID | null;
  classroomId: UUID | null;
};


// Signature Schema
export type SignatureResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "reason" | "ipAddress" | "userAgent" | "isVerified" | "insertedAt" | "updatedAt" | "petitionId" | "userId";
  id: UUIDv7;
  reason: string | null;
  ipAddress: string | null;
  userAgent: string | null;
  isVerified: boolean | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  petitionId: UUID;
  userId: UUID;
  petition: { __type: "Relationship"; __resource: PetitionResourceSchema; };
  user: { __type: "Relationship"; __resource: UserResourceSchema; };
};



export type SignatureAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "reason" | "ipAddress" | "userAgent" | "isVerified" | "insertedAt" | "updatedAt" | "petitionId" | "userId";
  id: UUIDv7;
  reason: string | null;
  ipAddress: string | null;
  userAgent: string | null;
  isVerified: boolean | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  petitionId: UUID;
  userId: UUID;
};


// Update Schema
export type UpdateResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "body" | "insertedAt" | "updatedAt" | "petitionId";
  id: UUIDv7;
  title: string;
  body: string;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  petitionId: UUID | null;
  petition: { __type: "Relationship"; __resource: PetitionResourceSchema | null; };
};



export type UpdateAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "body" | "insertedAt" | "updatedAt" | "petitionId";
  id: UUIDv7;
  title: string;
  body: string;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  petitionId: UUID | null;
};


export type NotificationFilterInput = {
  and?: Array<NotificationFilterInput>;
  or?: Array<NotificationFilterInput>;
  not?: Array<NotificationFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  body?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  status?: {
    eq?: "archived" | "read" | "unread";
    notEq?: "archived" | "read" | "unread";
    in?: Array<"archived" | "read" | "unread">;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type OrganizationFilterInput = {
  and?: Array<OrganizationFilterInput>;
  or?: Array<OrganizationFilterInput>;
  not?: Array<OrganizationFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  domain?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  logoUrl?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  allowPublicSignatures?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type PreferenceFilterInput = {
  and?: Array<PreferenceFilterInput>;
  or?: Array<PreferenceFilterInput>;
  not?: Array<PreferenceFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  value?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type UserFilterInput = {
  and?: Array<UserFilterInput>;
  or?: Array<UserFilterInput>;
  not?: Array<UserFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  firstName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  lastName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  email?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  graduationYear?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  role?: {
    eq?: "admin" | "professor" | "student";
    notEq?: "admin" | "professor" | "student";
    in?: Array<"admin" | "professor" | "student">;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  totalPetitionSignatures?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  numPetitions?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  numSigned?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  numPetitionSignees?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  petitions?: PetitionFilterInput;

  signatures?: SignatureFilterInput;

  classroomMemberships?: ClassroomMembershipFilterInput;

  ownedClassrooms?: ClassroomFilterInput;

};
export type CategoryFilterInput = {
  and?: Array<CategoryFilterInput>;
  or?: Array<CategoryFilterInput>;
  not?: Array<CategoryFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  color?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type ClassroomFilterInput = {
  and?: Array<ClassroomFilterInput>;
  or?: Array<ClassroomFilterInput>;
  not?: Array<ClassroomFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  joinCode?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  archived?: {
    eq?: boolean;
    notEq?: boolean;
  };

  allowStudentPetitions?: {
    eq?: boolean;
    notEq?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  professorId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  organizationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  memberCount?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  petitionCount?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };


  professor?: UserFilterInput;

  organization?: OrganizationFilterInput;

  memberships?: ClassroomMembershipFilterInput;

  petitions?: PetitionFilterInput;

};
export type ClassroomMembershipFilterInput = {
  and?: Array<ClassroomMembershipFilterInput>;
  or?: Array<ClassroomMembershipFilterInput>;
  not?: Array<ClassroomMembershipFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  role?: {
    eq?: "student" | "ta";
    notEq?: "student" | "ta";
    in?: Array<"student" | "ta">;
  };

  status?: {
    eq?: "active" | "pending" | "removed";
    notEq?: "active" | "pending" | "removed";
    in?: Array<"active" | "pending" | "removed">;
  };

  joinedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  classroomId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  invitedById?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };


  classroom?: ClassroomFilterInput;

  user?: UserFilterInput;

  invitedBy?: UserFilterInput;

};
export type CommentFilterInput = {
  and?: Array<CommentFilterInput>;
  or?: Array<CommentFilterInput>;
  not?: Array<CommentFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  text?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  sentiment?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };


  user?: UserFilterInput;

};
export type PetitionFilterInput = {
  and?: Array<PetitionFilterInput>;
  or?: Array<PetitionFilterInput>;
  not?: Array<PetitionFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  status?: {
    eq?: "closed" | "open" | "victory";
    notEq?: "closed" | "open" | "victory";
    in?: Array<"closed" | "open" | "victory">;
    isNil?: boolean;
  };

  goal?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  allowComments?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };

  isAnonymous?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };

  deadline?: {
    eq?: UtcDateTime;
    notEq?: UtcDateTime;
    greaterThan?: UtcDateTime;
    greaterThanOrEqual?: UtcDateTime;
    lessThan?: UtcDateTime;
    lessThanOrEqual?: UtcDateTime;
    in?: Array<UtcDateTime>;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  categoryId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  classroomId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  signaturesCount?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  isClassroomPetition?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };

  daysLeft?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  author?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  trending?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };


  user?: UserFilterInput;

  category?: CategoryFilterInput;

  classroom?: ClassroomFilterInput;

  updates?: UpdateFilterInput;

  comments?: CommentFilterInput;

  signatures?: SignatureFilterInput;

};
export type SignatureFilterInput = {
  and?: Array<SignatureFilterInput>;
  or?: Array<SignatureFilterInput>;
  not?: Array<SignatureFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  reason?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  ipAddress?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  userAgent?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  isVerified?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  petitionId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  petition?: PetitionFilterInput;

  user?: UserFilterInput;

};
export type UpdateFilterInput = {
  and?: Array<UpdateFilterInput>;
  or?: Array<UpdateFilterInput>;
  not?: Array<UpdateFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  body?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  petitionId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };


  petition?: PetitionFilterInput;

};


export const notificationFilterFields = ["id", "title", "body", "status", "insertedAt", "updatedAt"] as const;
export type NotificationFilterField = (typeof notificationFilterFields)[number];

export const organizationFilterFields = ["id", "name", "description", "domain", "logoUrl", "allowPublicSignatures", "insertedAt", "updatedAt"] as const;
export type OrganizationFilterField = (typeof organizationFilterFields)[number];

export const preferenceFilterFields = ["id", "name", "value", "insertedAt", "updatedAt"] as const;
export type PreferenceFilterField = (typeof preferenceFilterFields)[number];

export const userFilterFields = ["id", "firstName", "lastName", "email", "graduationYear", "role", "insertedAt", "updatedAt", "totalPetitionSignatures", "numPetitions", "numSigned", "numPetitionSignees", "petitions", "signatures", "classroomMemberships", "ownedClassrooms"] as const;
export type UserFilterField = (typeof userFilterFields)[number];

export const categoryFilterFields = ["id", "name", "description", "color", "insertedAt", "updatedAt"] as const;
export type CategoryFilterField = (typeof categoryFilterFields)[number];

export const classroomFilterFields = ["id", "name", "description", "joinCode", "archived", "allowStudentPetitions", "insertedAt", "updatedAt", "professorId", "organizationId", "memberCount", "petitionCount", "professor", "organization", "memberships", "petitions"] as const;
export type ClassroomFilterField = (typeof classroomFilterFields)[number];

export const classroomMembershipFilterFields = ["id", "role", "status", "joinedAt", "insertedAt", "updatedAt", "classroomId", "userId", "invitedById", "classroom", "user", "invitedBy"] as const;
export type ClassroomMembershipFilterField = (typeof classroomMembershipFilterFields)[number];

export const commentFilterFields = ["id", "text", "sentiment", "insertedAt", "updatedAt", "userId", "user"] as const;
export type CommentFilterField = (typeof commentFilterFields)[number];

export const petitionFilterFields = ["id", "title", "description", "status", "goal", "allowComments", "isAnonymous", "deadline", "insertedAt", "updatedAt", "userId", "categoryId", "classroomId", "signaturesCount", "isClassroomPetition", "daysLeft", "author", "trending", "user", "category", "classroom", "updates", "comments", "signatures"] as const;
export type PetitionFilterField = (typeof petitionFilterFields)[number];

export const signatureFilterFields = ["id", "reason", "ipAddress", "userAgent", "isVerified", "insertedAt", "updatedAt", "petitionId", "userId", "petition", "user"] as const;
export type SignatureFilterField = (typeof signatureFilterFields)[number];

export const updateFilterFields = ["id", "title", "body", "insertedAt", "updatedAt", "petitionId", "petition"] as const;
export type UpdateFilterField = (typeof updateFilterFields)[number];


export const notificationSortFields = ["id", "title", "body", "status", "insertedAt", "updatedAt"] as const;
export type NotificationSortField = (typeof notificationSortFields)[number];

export const organizationSortFields = ["id", "name", "description", "domain", "logoUrl", "allowPublicSignatures", "insertedAt", "updatedAt"] as const;
export type OrganizationSortField = (typeof organizationSortFields)[number];

export const preferenceSortFields = ["id", "name", "value", "insertedAt", "updatedAt"] as const;
export type PreferenceSortField = (typeof preferenceSortFields)[number];

export const userSortFields = ["id", "firstName", "lastName", "email", "graduationYear", "role", "insertedAt", "updatedAt", "totalPetitionSignatures", "numPetitions", "numSigned", "numPetitionSignees"] as const;
export type UserSortField = (typeof userSortFields)[number];

export const categorySortFields = ["id", "name", "description", "color", "insertedAt", "updatedAt"] as const;
export type CategorySortField = (typeof categorySortFields)[number];

export const classroomSortFields = ["id", "name", "description", "joinCode", "archived", "allowStudentPetitions", "insertedAt", "updatedAt", "professorId", "organizationId", "memberCount", "petitionCount"] as const;
export type ClassroomSortField = (typeof classroomSortFields)[number];

export const classroomMembershipSortFields = ["id", "role", "status", "joinedAt", "insertedAt", "updatedAt", "classroomId", "userId", "invitedById"] as const;
export type ClassroomMembershipSortField = (typeof classroomMembershipSortFields)[number];

export const commentSortFields = ["id", "text", "sentiment", "insertedAt", "updatedAt", "userId"] as const;
export type CommentSortField = (typeof commentSortFields)[number];

export const petitionSortFields = ["id", "title", "description", "status", "goal", "allowComments", "isAnonymous", "deadline", "insertedAt", "updatedAt", "userId", "categoryId", "classroomId", "signaturesCount", "isClassroomPetition", "daysLeft", "author", "trending"] as const;
export type PetitionSortField = (typeof petitionSortFields)[number];

export const signatureSortFields = ["id", "reason", "ipAddress", "userAgent", "isVerified", "insertedAt", "updatedAt", "petitionId", "userId"] as const;
export type SignatureSortField = (typeof signatureSortFields)[number];

export const updateSortFields = ["id", "title", "body", "insertedAt", "updatedAt", "petitionId"] as const;
export type UpdateSortField = (typeof updateSortFields)[number];


// Utility Types

// Sort string type — allows optional direction prefix on sort field names
// Prefixes per Ash.Query.sort/3: + (asc), - (desc), ++ (asc_nils_first), -- (desc_nils_last)
export type SortString<T extends string> = T | `+${T}` | `-${T}` | `++${T}` | `--${T}`;

// Resource schema constraint
export type TypedSchema = {
  __type: "Resource" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
export type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends UnionSchema["__primitiveFields"]
      ? FieldSelection[FieldIndex] extends keyof UnionSchema
        ? { [P in FieldSelection[FieldIndex]]: UnionSchema[FieldSelection[FieldIndex]] }
        : never
      : FieldSelection[FieldIndex] extends Record<string, any>
        ? {
            [UnionKey in keyof FieldSelection[FieldIndex]]: UnionKey extends keyof UnionSchema
              ? NonNullable<UnionSchema[UnionKey]> extends { __array: true; __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                ? FieldSelection[FieldIndex][UnionKey] extends any[]
                  ? Array<
                      UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      >
                    > | null
                  : never
                : NonNullable<UnionSchema[UnionKey]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                  ? FieldSelection[FieldIndex][UnionKey] extends any[]
                    ? UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      > | null
                    : never
                  : NonNullable<UnionSchema[UnionKey]> extends TypedSchema
                    ? InferResult<NonNullable<UnionSchema[UnionKey]>, FieldSelection[FieldIndex][UnionKey]>
                    : never
              : never;
          }
        : never;
  }[number]
>;

export type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

export type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

export type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

export type ComplexFieldSelection<T extends TypedSchema> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? UnifiedFieldSelection<NonNullable<Resource>>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>>[] }
          : never
      : T[K] extends { __type: "TypedMap" }
        ? NonNullable<T[K]> extends TypedSchema
          ? UnifiedFieldSelection<NonNullable<T[K]>>[]
          : never
        : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
          ? T[K] extends { __array: true }
            ? (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : NonNullable<T[K]> extends TypedSchema
              ? UnifiedFieldSelection<NonNullable<T[K]>>[]
              : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
export type UnifiedFieldSelection<T extends TypedSchema> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T>; // Recursive case

export type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? T[K] extends { __array: true }
                ? Array<InferResult<NonNullable<Resource>, Field[K]>>
                : null extends Resource
                  ? InferResult<NonNullable<Resource>, Field[K]> | null
                  : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : NonNullable<T[K]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
              ? NonNullable<T[K]> extends { __array: true }
                ? Field[K] extends any[]
                  ? null extends T[K]
                    ? Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      > | null
                    : Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      >
                  : never
                : Field[K] extends any[]
                  ? null extends T[K]
                    ? UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof NonNullable<T[K]>
                                ? { [P in E]: NonNullable<T[K]>[P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      > | null
                    : UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof T[K]
                                ? { [P in E]: T[K][P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      >
                  : never
              : T[K] extends { __type: "Union"; __primitiveFields: any }
                ? T[K] extends { __array: true }
                  ? Field[K] extends any[]
                    ? null extends T[K]
                      ? Array<InferUnionFieldValue<T[K], Field[K]>> | null
                      : Array<InferUnionFieldValue<T[K], Field[K]>>
                    : never
                  : Field[K] extends any[]
                    ? null extends T[K]
                      ? InferUnionFieldValue<T[K], Field[K]> | null
                      : InferUnionFieldValue<T[K], Field[K]>
                    : never
                  : NonNullable<T[K]> extends TypedSchema
                    ? null extends T[K]
                      ? InferResult<NonNullable<T[K]>, Field[K]> | null
                      : InferResult<NonNullable<T[K]>, Field[K]>
                    : never
          : never;
      }
    : never;

export type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters
export type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  false;

// Infer which pagination type is being used from the page config
export type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
export type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call.
 *
 * This type matches the error structure defined in the AshTypescript.Rpc.Error protocol.
 *
 * @example
 * const error: AshRpcError = {
 *   type: "invalid_changes",
 *   message: "Invalid value for field %{field}",
 *   shortMessage: "Invalid changes",
 *   vars: { field: "email" },
 *   fields: ["email"],
 *   path: ["user", "email"],
 *   details: { suggestion: "Provide a valid email address" }
 * }
 */
export type AshRpcError = {
  /** Machine-readable error type (e.g., "invalid_changes", "not_found") */
  type: string;
  /** Full error message (may contain template variables like %{key}) */
  message: string;
  /** Concise version of the message */
  shortMessage: string;
  /** Variables to interpolate into the message template */
  vars: Record<string, any>;
  /** List of affected field names (for field-level errors) */
  fields: string[];
  /** Path to the error location in the data structure */
  path: string[];
  /** Optional map with extra details (e.g., suggestions, hints) */
  details?: Record<string, any>;
}

/**
 * Represents the result of a validation RPC call.
 *
 * All validation actions return this same structure, indicating either
 * successful validation or a list of validation errors.
 *
 * @example
 * // Successful validation
 * const result: ValidationResult = { success: true };
 *
 * // Failed validation
 * const result: ValidationResult = {
 *   success: false,
 *   errors: [
 *     {
 *       type: "required",
 *       message: "is required",
 *       shortMessage: "Required field",
 *       vars: { field: "email" },
 *       fields: ["email"],
 *       path: []
 *     }
 *   ]
 * };
 */
export type ValidationResult =
  | { success: true }
  | { success: false; errors: AshRpcError[]; };




