// Generated by AshTypescript
// Do not edit this file manually





export type UUIDv7 = string;
export type UUID = string;
export type UtcDateTime = string;
export type UtcDateTimeUsec = string;

// Organization Schema
export type OrganizationResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "description" | "domain" | "logoUrl" | "allowPublicSignatures" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  name: string | null;
  description: string | null;
  domain: string | null;
  logoUrl: string | null;
  allowPublicSignatures: boolean | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



// User Schema
export type UserResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "firstName" | "lastName" | "email" | "graduationYear" | "insertedAt" | "updatedAt" | "numPetitions" | "numSigned" | "numPetitionSignees" | "totalPetitionSignatures";
  id: UUID;
  firstName: string | null;
  lastName: string | null;
  email: string;
  graduationYear: number | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  numPetitions: number;
  numSigned: number;
  numPetitionSignees: number;
  totalPetitionSignatures: number | null;
  petitions: { __type: "Relationship"; __array: true; __resource: PetitionResourceSchema; };
  signatures: { __type: "Relationship"; __array: true; __resource: SignatureResourceSchema; };
};



// Preference Schema
export type PreferenceResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "value" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  name: string | null;
  value: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



// Notification Schema
export type NotificationResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "body" | "status" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  title: string;
  body: string | null;
  status: "unread" | "read" | "archived";
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



// Petition Schema
export type PetitionResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "description" | "status" | "goal" | "allowComments" | "isAnonymous" | "deadline" | "insertedAt" | "updatedAt" | "userId" | "categoryId" | "signaturesCount" | "daysLeft" | "author" | "trending";
  id: UUIDv7;
  title: string | null;
  description: string | null;
  status: "open" | "closed" | "victory" | null;
  goal: number | null;
  allowComments: boolean | null;
  isAnonymous: boolean | null;
  deadline: UtcDateTime | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  userId: UUID | null;
  categoryId: UUID | null;
  signaturesCount: number | null;
  daysLeft: number | null;
  author: string | null;
  trending: boolean | null;
  user: { __type: "Relationship"; __resource: UserResourceSchema | null; };
  category: { __type: "Relationship"; __resource: CategoryResourceSchema | null; };
  updates: { __type: "Relationship"; __array: true; __resource: UpdateResourceSchema; };
  comments: { __type: "Relationship"; __array: true; __resource: CommentResourceSchema; };
  signatures: { __type: "Relationship"; __array: true; __resource: SignatureResourceSchema; };
};



// Update Schema
export type UpdateResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "body" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  title: string;
  body: string;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



// Signature Schema
export type SignatureResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "reason" | "ipAddress" | "userAgent" | "isVerified" | "insertedAt" | "updatedAt" | "petitionId" | "userId";
  id: UUIDv7;
  reason: string | null;
  ipAddress: string | null;
  userAgent: string | null;
  isVerified: boolean | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  petitionId: UUID;
  userId: UUID;
  petition: { __type: "Relationship"; __resource: PetitionResourceSchema; };
  user: { __type: "Relationship"; __resource: UserResourceSchema; };
};



// Comment Schema
export type CommentResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "text" | "sentiment" | "insertedAt" | "updatedAt" | "userId";
  id: UUIDv7;
  text: string | null;
  sentiment: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  userId: UUID | null;
  user: { __type: "Relationship"; __resource: UserResourceSchema | null; };
};



// Category Schema
export type CategoryResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "description" | "color" | "insertedAt" | "updatedAt";
  id: UUIDv7;
  name: string | null;
  description: string | null;
  color: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};





export type OrganizationFilterInput = {
  and?: Array<OrganizationFilterInput>;
  or?: Array<OrganizationFilterInput>;
  not?: Array<OrganizationFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  domain?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  logoUrl?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  allowPublicSignatures?: {
    eq?: boolean;
    notEq?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type UserFilterInput = {
  and?: Array<UserFilterInput>;
  or?: Array<UserFilterInput>;
  not?: Array<UserFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  firstName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  lastName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  email?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  graduationYear?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  totalPetitionSignatures?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  numPetitions?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  numSigned?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  numPetitionSignees?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  petitions?: PetitionFilterInput;

  signatures?: SignatureFilterInput;

};
export type PreferenceFilterInput = {
  and?: Array<PreferenceFilterInput>;
  or?: Array<PreferenceFilterInput>;
  not?: Array<PreferenceFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  value?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type NotificationFilterInput = {
  and?: Array<NotificationFilterInput>;
  or?: Array<NotificationFilterInput>;
  not?: Array<NotificationFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  body?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  status?: {
    eq?: "unread" | "read" | "archived";
    notEq?: "unread" | "read" | "archived";
    in?: Array<"unread" | "read" | "archived">;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type PetitionFilterInput = {
  and?: Array<PetitionFilterInput>;
  or?: Array<PetitionFilterInput>;
  not?: Array<PetitionFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  status?: {
    eq?: "open" | "closed" | "victory";
    notEq?: "open" | "closed" | "victory";
    in?: Array<"open" | "closed" | "victory">;
  };

  goal?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  allowComments?: {
    eq?: boolean;
    notEq?: boolean;
  };

  isAnonymous?: {
    eq?: boolean;
    notEq?: boolean;
  };

  deadline?: {
    eq?: UtcDateTime;
    notEq?: UtcDateTime;
    greaterThan?: UtcDateTime;
    greaterThanOrEqual?: UtcDateTime;
    lessThan?: UtcDateTime;
    lessThanOrEqual?: UtcDateTime;
    in?: Array<UtcDateTime>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  categoryId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  signaturesCount?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  daysLeft?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  author?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  trending?: {
    eq?: boolean;
    notEq?: boolean;
  };


  user?: UserFilterInput;

  category?: CategoryFilterInput;

  updates?: UpdateFilterInput;

  comments?: CommentFilterInput;

  signatures?: SignatureFilterInput;

};
export type UpdateFilterInput = {
  and?: Array<UpdateFilterInput>;
  or?: Array<UpdateFilterInput>;
  not?: Array<UpdateFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  body?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type SignatureFilterInput = {
  and?: Array<SignatureFilterInput>;
  or?: Array<SignatureFilterInput>;
  not?: Array<SignatureFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  reason?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  ipAddress?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  userAgent?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  isVerified?: {
    eq?: boolean;
    notEq?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  petitionId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  petition?: PetitionFilterInput;

  user?: UserFilterInput;

};
export type CommentFilterInput = {
  and?: Array<CommentFilterInput>;
  or?: Array<CommentFilterInput>;
  not?: Array<CommentFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  text?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  sentiment?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  user?: UserFilterInput;

};
export type CategoryFilterInput = {
  and?: Array<CategoryFilterInput>;
  or?: Array<CategoryFilterInput>;
  not?: Array<CategoryFilterInput>;

  id?: {
    eq?: UUIDv7;
    notEq?: UUIDv7;
    in?: Array<UUIDv7>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  color?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};


// Utility Types

// Resource schema constraint
type TypedSchema = {
  __type: "Resource" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends UnionSchema["__primitiveFields"]
      ? FieldSelection[FieldIndex] extends keyof UnionSchema
        ? { [P in FieldSelection[FieldIndex]]: UnionSchema[FieldSelection[FieldIndex]] }
        : never
      : FieldSelection[FieldIndex] extends Record<string, any>
        ? {
            [UnionKey in keyof FieldSelection[FieldIndex]]: UnionKey extends keyof UnionSchema
              ? UnionSchema[UnionKey] extends { __array: true; __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                ? FieldSelection[FieldIndex][UnionKey] extends any[]
                  ? Array<
                      UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof UnionSchema[UnionKey]
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: UnionSchema[UnionKey][P] }
                              : never
                            : never;
                        }[number]
                      >
                    > | null
                  : never
                : UnionSchema[UnionKey] extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                  ? FieldSelection[FieldIndex][UnionKey] extends any[]
                    ? UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof UnionSchema[UnionKey]
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: UnionSchema[UnionKey][P] }
                              : never
                            : never;
                        }[number]
                      > | null
                    : never
                  : UnionSchema[UnionKey] extends TypedSchema
                    ? InferResult<UnionSchema[UnionKey], FieldSelection[FieldIndex][UnionKey]>
                    : never
              : never;
          }
        : never;
  }[number]
>;

type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

type ComplexFieldSelection<T extends TypedSchema> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? UnifiedFieldSelection<NonNullable<Resource>>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>>[] }
          : never
      : T[K] extends { __type: "TypedMap"; __primitiveFields: infer PrimitiveFields }
        ? PrimitiveFields[]
        : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
          ? T[K] extends { __array: true }
            ? (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: T[K][UnionKey] extends { __type: "TypedMap"; __primitiveFields: any }
                  ? T[K][UnionKey]["__primitiveFields"][]
                  : T[K][UnionKey] extends TypedSchema
                    ? UnifiedFieldSelection<T[K][UnionKey]>[]
                    : never;
              })[]
            : (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: T[K][UnionKey] extends TypedSchema
                  ? T[K][UnionKey]["__primitiveFields"][]
                  : T[K][UnionKey] extends TypedSchema
                    ? UnifiedFieldSelection<T[K][UnionKey]>[]
                    : never;
              })[]
            : NonNullable<T[K]> extends TypedSchema
              ? UnifiedFieldSelection<NonNullable<T[K]>>[]
              : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
type UnifiedFieldSelection<T extends TypedSchema> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T>; // Recursive case

type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? T[K] extends { __array: true }
                ? Array<InferResult<NonNullable<Resource>, Field[K]>>
                : null extends Resource
                  ? InferResult<NonNullable<Resource>, Field[K]> | null
                  : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : NonNullable<T[K]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
              ? NonNullable<T[K]> extends { __array: true }
                ? Field[K] extends any[]
                  ? null extends T[K]
                    ? Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends TypedMapFields
                              ? Field[K][FieldIndex] extends keyof NonNullable<T[K]>
                                ? { [P in Field[K][FieldIndex]]: NonNullable<T[K]>[P] }
                                : never
                              : never;
                          }[number]
                        >
                      > | null
                    : Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends TypedMapFields
                              ? Field[K][FieldIndex] extends keyof NonNullable<T[K]>
                                ? { [P in Field[K][FieldIndex]]: NonNullable<T[K]>[P] }
                                : never
                              : never;
                          }[number]
                        >
                      >
                  : never
                : Field[K] extends any[]
                  ? null extends T[K]
                    ? UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends TypedMapFields
                            ? Field[K][FieldIndex] extends keyof NonNullable<T[K]>
                              ? { [P in Field[K][FieldIndex]]: NonNullable<T[K]>[P] }
                              : never
                            : never;
                        }[number]
                      > | null
                    : UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends TypedMapFields
                            ? Field[K][FieldIndex] extends keyof T[K]
                              ? { [P in Field[K][FieldIndex]]: T[K][P] }
                              : never
                            : never;
                        }[number]
                      >
                  : never
              : T[K] extends { __type: "Union"; __primitiveFields: any }
                ? T[K] extends { __array: true }
                  ? {
                      [CurrentK in K]: T[CurrentK] extends { __type: "Union"; __primitiveFields: any }
                        ? Field[CurrentK] extends any[]
                          ? Array<InferUnionFieldValue<T[CurrentK], Field[CurrentK]>> | null
                          : never
                        : never
                    }
                  : {
                      [CurrentK in K]: T[CurrentK] extends { __type: "Union"; __primitiveFields: any }
                        ? Field[CurrentK] extends any[]
                          ? InferUnionFieldValue<T[CurrentK], Field[CurrentK]> | null
                          : never
                        : never
                    }
                  : NonNullable<T[K]> extends TypedSchema
                    ? null extends T[K]
                      ? InferResult<NonNullable<T[K]>, Field[K]> | null
                      : InferResult<NonNullable<T[K]>, Field[K]>
                    : never
          : never;
      }
    : never;

type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters
type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  false;

// Infer which pagination type is being used from the page config
type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call.
 *
 * This type matches the error structure defined in the AshTypescript.Rpc.Error protocol.
 *
 * @example
 * const error: AshRpcError = {
 *   type: "invalid_changes",
 *   message: "Invalid value for field %{field}",
 *   shortMessage: "Invalid changes",
 *   vars: { field: "email" },
 *   fields: ["email"],
 *   path: ["user", "email"],
 *   details: { suggestion: "Provide a valid email address" }
 * }
 */
export type AshRpcError = {
  /** Machine-readable error type (e.g., "invalid_changes", "not_found") */
  type: string;
  /** Full error message (may contain template variables like %{key}) */
  message: string;
  /** Concise version of the message */
  shortMessage: string;
  /** Variables to interpolate into the message template */
  vars: Record<string, any>;
  /** List of affected field names (for field-level errors) */
  fields: string[];
  /** Path to the error location in the data structure */
  path: string[];
  /** Optional map with extra details (e.g., suggestions, hints) */
  details?: Record<string, any>;
}

/**
 * Represents the result of a validation RPC call.
 *
 * All validation actions return this same structure, indicating either
 * successful validation or a list of validation errors.
 *
 * @example
 * // Successful validation
 * const result: ValidationResult = { success: true };
 *
 * // Failed validation
 * const result: ValidationResult = {
 *   success: false,
 *   errors: [
 *     {
 *       type: "required",
 *       message: "is required",
 *       shortMessage: "Required field",
 *       vars: { field: "email" },
 *       fields: ["email"],
 *       path: []
 *     }
 *   ]
 * };
 */
export type ValidationResult =
  | { success: true }
  | { success: false; errors: AshRpcError[]; };





// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  primaryKey?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...config.headers,
    ...processedConfig.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...config.fetchOptions,
    ...processedConfig.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...config.headers,
    ...processedConfig.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...config.fetchOptions,
    ...processedConfig.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}









export type GetOrganizationsFields = UnifiedFieldSelection<OrganizationResourceSchema>[];


export type InferGetOrganizationsResult<
  Fields extends GetOrganizationsFields | undefined,
  Page extends GetOrganizationsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<OrganizationResourceSchema, Fields>>, {
  results: Array<InferResult<OrganizationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<OrganizationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetOrganizationsConfig = {
  fields: GetOrganizationsFields;
  filter?: OrganizationFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetOrganizationsResult<Fields extends GetOrganizationsFields, Page extends GetOrganizationsConfig["page"] = undefined> = | { success: true; data: InferGetOrganizationsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

export async function getOrganizations<Fields extends GetOrganizationsFields, Config extends GetOrganizationsConfig = GetOrganizationsConfig>(
  config: Config & { fields: Fields }
): Promise<GetOrganizationsResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_organizations",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetOrganizationsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export async function validateGetOrganizations(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_organizations"
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetUsersInput = {
  firstName?: string;
  lastName?: string;
  email?: string;
};

export type GetUsersFields = UnifiedFieldSelection<UserResourceSchema>[];
export type InferGetUsersResult<
  Fields extends GetUsersFields,
> = Array<InferResult<UserResourceSchema, Fields>>;

export type GetUsersResult<Fields extends GetUsersFields> = | { success: true; data: InferGetUsersResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

export async function getUsers<Fields extends GetUsersFields>(
  config: {
  input?: GetUsersInput;
  fields: Fields;
  filter?: UserFilterInput;
  sort?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetUsersResult<Fields>> {
  const payload = {
    action: "get_users",
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort })
  };

  return executeActionRpcRequest<GetUsersResult<Fields>>(
    payload,
    config
  );
}


export async function validateGetUsers(
  config: {
  input?: GetUsersInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_users",
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetUserByIdInput = {
  id?: UUID;
  includeStats?: boolean;
};

export type GetUserByIdFields = UnifiedFieldSelection<UserResourceSchema>[];
export type InferGetUserByIdResult<
  Fields extends GetUserByIdFields,
> = InferResult<UserResourceSchema, Fields> | null;

export type GetUserByIdResult<Fields extends GetUserByIdFields> = | { success: true; data: InferGetUserByIdResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

export async function getUserById<Fields extends GetUserByIdFields>(
  config: {
  input?: GetUserByIdInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetUserByIdResult<Fields>> {
  const payload = {
    action: "get_user_by_id",
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetUserByIdResult<Fields>>(
    payload,
    config
  );
}


export async function validateGetUserById(
  config: {
  input?: GetUserByIdInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_user_by_id",
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetPreferencesFields = UnifiedFieldSelection<PreferenceResourceSchema>[];


export type InferGetPreferencesResult<
  Fields extends GetPreferencesFields | undefined,
  Page extends GetPreferencesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<PreferenceResourceSchema, Fields>>, {
  results: Array<InferResult<PreferenceResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<PreferenceResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetPreferencesConfig = {
  fields: GetPreferencesFields;
  filter?: PreferenceFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetPreferencesResult<Fields extends GetPreferencesFields, Page extends GetPreferencesConfig["page"] = undefined> = | { success: true; data: InferGetPreferencesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

export async function getPreferences<Fields extends GetPreferencesFields, Config extends GetPreferencesConfig = GetPreferencesConfig>(
  config: Config & { fields: Fields }
): Promise<GetPreferencesResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_preferences",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetPreferencesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export async function validateGetPreferences(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_preferences"
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetNotificationsFields = UnifiedFieldSelection<NotificationResourceSchema>[];


export type InferGetNotificationsResult<
  Fields extends GetNotificationsFields | undefined,
  Page extends GetNotificationsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<NotificationResourceSchema, Fields>>, {
  results: Array<InferResult<NotificationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<NotificationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetNotificationsConfig = {
  fields: GetNotificationsFields;
  filter?: NotificationFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetNotificationsResult<Fields extends GetNotificationsFields, Page extends GetNotificationsConfig["page"] = undefined> = | { success: true; data: InferGetNotificationsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

export async function getNotifications<Fields extends GetNotificationsFields, Config extends GetNotificationsConfig = GetNotificationsConfig>(
  config: Config & { fields: Fields }
): Promise<GetNotificationsResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_notifications",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetNotificationsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export async function validateGetNotifications(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_notifications"
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetPetitionsFields = UnifiedFieldSelection<PetitionResourceSchema>[];


export type InferGetPetitionsResult<
  Fields extends GetPetitionsFields | undefined,
  Page extends GetPetitionsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<PetitionResourceSchema, Fields>>, {
  results: Array<InferResult<PetitionResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<PetitionResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetPetitionsConfig = {
  fields: GetPetitionsFields;
  filter?: PetitionFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetPetitionsResult<Fields extends GetPetitionsFields, Page extends GetPetitionsConfig["page"] = undefined> = | { success: true; data: InferGetPetitionsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

export async function getPetitions<Fields extends GetPetitionsFields, Config extends GetPetitionsConfig = GetPetitionsConfig>(
  config: Config & { fields: Fields }
): Promise<GetPetitionsResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_petitions",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetPetitionsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export async function validateGetPetitions(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_petitions"
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetPetitionByIdInput = {
  id?: UUIDv7;
};

export type GetPetitionByIdFields = UnifiedFieldSelection<PetitionResourceSchema>[];
export type InferGetPetitionByIdResult<
  Fields extends GetPetitionByIdFields,
> = InferResult<PetitionResourceSchema, Fields> | null;

export type GetPetitionByIdResult<Fields extends GetPetitionByIdFields> = | { success: true; data: InferGetPetitionByIdResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

export async function getPetitionById<Fields extends GetPetitionByIdFields>(
  config: {
  input?: GetPetitionByIdInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetPetitionByIdResult<Fields>> {
  const payload = {
    action: "get_petition_by_id",
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetPetitionByIdResult<Fields>>(
    payload,
    config
  );
}


export async function validateGetPetitionById(
  config: {
  input?: GetPetitionByIdInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_petition_by_id",
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreatePetitionInput = {
  title?: string | null;
  description?: string | null;
  status?: "open" | "closed" | "victory" | null;
  goal?: number | null;
  deadline?: UtcDateTime | null;
  allowComments?: boolean | null;
  isAnonymous?: boolean | null;
  categoryId: UUIDv7;
};

export type CreatePetitionFields = UnifiedFieldSelection<PetitionResourceSchema>[];

export type InferCreatePetitionResult<
  Fields extends CreatePetitionFields | undefined,
> = InferResult<PetitionResourceSchema, Fields>;

export type CreatePetitionResult<Fields extends CreatePetitionFields | undefined = undefined> = | { success: true; data: InferCreatePetitionResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

export async function createPetition<Fields extends CreatePetitionFields | undefined = undefined>(
  config: {
  input: CreatePetitionInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreatePetitionResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_petition",
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreatePetitionResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


export async function validateCreatePetition(
  config: {
  input: CreatePetitionInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_petition",
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetUpdatesFields = UnifiedFieldSelection<UpdateResourceSchema>[];


export type InferGetUpdatesResult<
  Fields extends GetUpdatesFields | undefined,
  Page extends GetUpdatesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<UpdateResourceSchema, Fields>>, {
  results: Array<InferResult<UpdateResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<UpdateResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetUpdatesConfig = {
  fields: GetUpdatesFields;
  filter?: UpdateFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetUpdatesResult<Fields extends GetUpdatesFields, Page extends GetUpdatesConfig["page"] = undefined> = | { success: true; data: InferGetUpdatesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

export async function getUpdates<Fields extends GetUpdatesFields, Config extends GetUpdatesConfig = GetUpdatesConfig>(
  config: Config & { fields: Fields }
): Promise<GetUpdatesResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_updates",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetUpdatesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export async function validateGetUpdates(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_updates"
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetSignaturesFields = UnifiedFieldSelection<SignatureResourceSchema>[];


export type InferGetSignaturesResult<
  Fields extends GetSignaturesFields | undefined,
  Page extends GetSignaturesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<SignatureResourceSchema, Fields>>, {
  results: Array<InferResult<SignatureResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<SignatureResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetSignaturesConfig = {
  fields: GetSignaturesFields;
  filter?: SignatureFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetSignaturesResult<Fields extends GetSignaturesFields, Page extends GetSignaturesConfig["page"] = undefined> = | { success: true; data: InferGetSignaturesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

export async function getSignatures<Fields extends GetSignaturesFields, Config extends GetSignaturesConfig = GetSignaturesConfig>(
  config: Config & { fields: Fields }
): Promise<GetSignaturesResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_signatures",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetSignaturesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export async function validateGetSignatures(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_signatures"
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateSignatureInput = {
  reason?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  isVerified?: boolean | null;
  petitionId: UUID;
  userId: UUID;
};

export type CreateSignatureFields = UnifiedFieldSelection<SignatureResourceSchema>[];

export type InferCreateSignatureResult<
  Fields extends CreateSignatureFields | undefined,
> = InferResult<SignatureResourceSchema, Fields>;

export type CreateSignatureResult<Fields extends CreateSignatureFields | undefined = undefined> = | { success: true; data: InferCreateSignatureResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

export async function createSignature<Fields extends CreateSignatureFields | undefined = undefined>(
  config: {
  input: CreateSignatureInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateSignatureResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_signature",
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateSignatureResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


export async function validateCreateSignature(
  config: {
  input: CreateSignatureInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_signature",
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetCommentsFields = UnifiedFieldSelection<CommentResourceSchema>[];


export type InferGetCommentsResult<
  Fields extends GetCommentsFields | undefined,
  Page extends GetCommentsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<CommentResourceSchema, Fields>>, {
  results: Array<InferResult<CommentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<CommentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetCommentsConfig = {
  fields: GetCommentsFields;
  filter?: CommentFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetCommentsResult<Fields extends GetCommentsFields, Page extends GetCommentsConfig["page"] = undefined> = | { success: true; data: InferGetCommentsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

export async function getComments<Fields extends GetCommentsFields, Config extends GetCommentsConfig = GetCommentsConfig>(
  config: Config & { fields: Fields }
): Promise<GetCommentsResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_comments",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetCommentsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export async function validateGetComments(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_comments"
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CreateCommentInput = {
  text?: string | null;
  parentCommentId?: UUIDv7 | null;
  petitionId: UUID;
  userId: UUID;
};

export type CreateCommentFields = UnifiedFieldSelection<CommentResourceSchema>[];

export type InferCreateCommentResult<
  Fields extends CreateCommentFields | undefined,
> = InferResult<CommentResourceSchema, Fields>;

export type CreateCommentResult<Fields extends CreateCommentFields | undefined = undefined> = | { success: true; data: InferCreateCommentResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

export async function createComment<Fields extends CreateCommentFields | undefined = undefined>(
  config: {
  input: CreateCommentInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateCommentResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_comment",
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateCommentResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


export async function validateCreateComment(
  config: {
  input: CreateCommentInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "create_comment",
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetCategoriesFields = UnifiedFieldSelection<CategoryResourceSchema>[];


export type InferGetCategoriesResult<
  Fields extends GetCategoriesFields | undefined,
  Page extends GetCategoriesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<CategoryResourceSchema, Fields>>, {
  results: Array<InferResult<CategoryResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<CategoryResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetCategoriesConfig = {
  fields: GetCategoriesFields;
  filter?: CategoryFilterInput;
  sort?: string;
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetCategoriesResult<Fields extends GetCategoriesFields, Page extends GetCategoriesConfig["page"] = undefined> = | { success: true; data: InferGetCategoriesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

export async function getCategories<Fields extends GetCategoriesFields, Config extends GetCategoriesConfig = GetCategoriesConfig>(
  config: Config & { fields: Fields }
): Promise<GetCategoriesResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_categories",
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetCategoriesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export async function validateGetCategories(
  config: {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_categories"
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


