defmodule Petitionu.Repo.Migrations.SwapTimestamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    rename table(:preference), :created_at, to: :inserted_at

    alter table(:preference) do
      modify :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      modify :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    rename table(:petition), :created_at, to: :inserted_at

    execute("UPDATE petition SET inserted_at = NOW() WHERE inserted_at IS NULL")
    execute("UPDATE petition SET updated_at = NOW() WHERE updated_at IS NULL")

    alter table(:petition) do
      modify :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      modify :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    rename table(:organization), :created_at, to: :inserted_at

    alter table(:organization) do
      modify :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      modify :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:notification) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    rename table(:comment), :created_at, to: :inserted_at

    alter table(:comment) do
      modify :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      modify :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:category) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:category) do
      remove :updated_at
      remove :inserted_at
    end

    alter table(:comment) do
      modify :inserted_at, :utc_datetime_usec, null: true, default: nil
      modify :updated_at, :utc_datetime_usec, null: true, default: nil
    end

    rename table(:comment), :inserted_at, to: :created_at

    alter table(:notification) do
      remove :updated_at
      remove :inserted_at
    end

    alter table(:organization) do
      modify :inserted_at, :utc_datetime_usec, null: true, default: nil
      modify :updated_at, :utc_datetime_usec, null: true, default: nil
    end

    rename table(:organization), :inserted_at, to: :created_at

    alter table(:petition) do
      modify :inserted_at, :utc_datetime_usec, null: true, default: nil
      modify :updated_at, :utc_datetime_usec, null: true, default: nil
    end

    rename table(:petition), :inserted_at, to: :created_at

    alter table(:preference) do
      modify :inserted_at, :utc_datetime_usec, null: true, default: nil
      modify :updated_at, :utc_datetime_usec, null: true, default: nil
    end

    rename table(:preference), :inserted_at, to: :created_at

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
    end
  end
end
