defmodule Petitionu.Repo.Migrations.AddGolangModels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :first_name, :text
      add :last_name, :text
      add :organization_id, :uuid
    end

    create table(:user_petitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "user_petitions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :petition_id,
          references(:petition,
            column: :id,
            name: "user_petitions_petition_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :relationship, :text, null: false, default: "signee"
      add :bookmarked, :boolean, null: false, default: false
      add :created_at, :utc_datetime_usec
      add :updated_at, :utc_datetime_usec
    end

    create table(:preference, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text
      add :value, :text
      add :created_at, :utc_datetime_usec
      add :updated_at, :utc_datetime_usec

      add :user_id,
          references(:users,
            column: :id,
            name: "preference_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    rename table(:petition), :body, to: :description

    alter table(:petition) do
      add :user_id,
          references(:users,
            column: :id,
            name: "petition_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:organization, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:users) do
      modify :organization_id,
             references(:organization,
               column: :id,
               name: "users_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organization) do
      add :name, :text
      add :description, :text
      add :domain, :text
      add :created_at, :utc_datetime_usec
      add :updated_at, :utc_datetime_usec
    end

    create table(:comment, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :text, :text
      add :sentiment, :text
      add :created_at, :utc_datetime_usec
      add :updated_at, :utc_datetime_usec

      add :user_id,
          references(:users,
            column: :id,
            name: "comment_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :petition_id,
          references(:petition,
            column: :id,
            name: "comment_petition_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:comment, "comment_user_id_fkey")

    drop constraint(:comment, "comment_petition_id_fkey")

    drop table(:comment)

    alter table(:organization) do
      remove :updated_at
      remove :created_at
      remove :domain
      remove :description
      remove :name
    end

    drop constraint(:users, "users_organization_id_fkey")

    alter table(:users) do
      modify :organization_id, :uuid
    end

    drop table(:organization)

    drop constraint(:petition, "petition_user_id_fkey")

    alter table(:petition) do
      remove :user_id
    end

    rename table(:petition), :description, to: :body

    drop constraint(:preference, "preference_user_id_fkey")

    drop table(:preference)

    drop constraint(:user_petitions, "user_petitions_user_id_fkey")

    drop constraint(:user_petitions, "user_petitions_petition_id_fkey")

    drop table(:user_petitions)

    alter table(:users) do
      remove :organization_id
      remove :last_name
      remove :first_name
    end
  end
end
