defmodule Petitionu.Repo.Migrations.AddPetitionFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:petition) do
      add :category, :text
      add :goal, :bigint, default: 1000
      add :trending, :boolean, default: false
    end
  end

  def down do
    alter table(:petition) do
      remove :trending
      remove :goal
      remove :category
    end
  end
end
