defmodule Petitionu.Repo.Migrations.AddClassrooms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :role, :text, null: false, default: "student"
    end

    alter table(:petition) do
      add :classroom_id, :uuid
    end

    create table(:classrooms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:petition) do
      modify :classroom_id,
             references(:classrooms,
               column: :id,
               name: "petition_classroom_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:classrooms) do
      add :name, :text, null: false
      add :description, :text
      add :join_code, :uuid, null: false
      add :archived, :boolean, null: false, default: false
      add :allow_student_petitions, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :professor_id,
          references(:users,
            column: :id,
            name: "classrooms_professor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :organization_id,
          references(:organization,
            column: :id,
            name: "classrooms_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:classrooms, [:join_code], name: "classrooms_unique_join_code_index")

    create table(:classroom_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :role, :text, null: false, default: "student"
      add :status, :text, null: false, default: "pending"
      add :joined_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :classroom_id,
          references(:classrooms,
            column: :id,
            name: "classroom_memberships_classroom_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "classroom_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :invited_by_id,
          references(:users,
            column: :id,
            name: "classroom_memberships_invited_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:classroom_memberships, [:classroom_id, :user_id],
             name: "classroom_memberships_unique_membership_index"
           )
  end

  def down do
    drop_if_exists unique_index(:classroom_memberships, [:classroom_id, :user_id],
                     name: "classroom_memberships_unique_membership_index"
                   )

    drop constraint(:classroom_memberships, "classroom_memberships_classroom_id_fkey")

    drop constraint(:classroom_memberships, "classroom_memberships_user_id_fkey")

    drop constraint(:classroom_memberships, "classroom_memberships_invited_by_id_fkey")

    drop table(:classroom_memberships)

    drop_if_exists unique_index(:classrooms, [:join_code],
                     name: "classrooms_unique_join_code_index"
                   )

    drop constraint(:classrooms, "classrooms_professor_id_fkey")

    drop constraint(:classrooms, "classrooms_organization_id_fkey")

    alter table(:classrooms) do
      remove :organization_id
      remove :professor_id
      remove :updated_at
      remove :inserted_at
      remove :allow_student_petitions
      remove :archived
      remove :join_code
      remove :description
      remove :name
    end

    drop constraint(:petition, "petition_classroom_id_fkey")

    alter table(:petition) do
      modify :classroom_id, :uuid
    end

    drop table(:classrooms)

    alter table(:petition) do
      remove :classroom_id
    end

    alter table(:users) do
      remove :role
    end
  end
end
