defmodule Petitionu.Repo.Migrations.AddSignature do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :student_id, :text
      add :graduation_year, :bigint
    end

    create table(:signature, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :reason, :text
      add :ip_address, :text
      add :user_agent, :text
      add :is_verified, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :petition_id,
          references(:petition,
            column: :id,
            name: "signature_petition_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "signature_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:signature, [:petition_id, :user_id],
             name: "signature_unique_signature_index"
           )

    alter table(:petition) do
      remove :trending
      remove :category
      modify :status, :text, default: "open"
      add :signature_count, :bigint, default: 0
      add :allow_comments, :boolean, default: true
      add :is_anonymous, :boolean, default: false
      add :category_id, :uuid
    end

    alter table(:organization) do
      add :logo_url, :text
      add :allow_public_signatures, :boolean, default: false
    end

    create table(:notification, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :reference_id, :text
      add :title, :text, null: false
      add :body, :text
      add :status, :text, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "notification_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:comment) do
      add :parent_comment_id, :uuid
    end

    create table(:category, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:petition) do
      modify :category_id,
             references(:category,
               column: :id,
               name: "petition_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:category) do
      add :name, :text
      add :description, :text
      add :color, :text, default: "#00683d"

      add :organization_id,
          references(:organization,
            column: :id,
            name: "category_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:category, "category_organization_id_fkey")

    alter table(:category) do
      remove :organization_id
      remove :color
      remove :description
      remove :name
    end

    drop constraint(:petition, "petition_category_id_fkey")

    alter table(:petition) do
      modify :category_id, :uuid
    end

    drop table(:category)

    alter table(:comment) do
      remove :parent_comment_id
    end

    drop constraint(:notification, "notification_user_id_fkey")

    drop table(:notification)

    alter table(:organization) do
      remove :allow_public_signatures
      remove :logo_url
    end

    alter table(:petition) do
      remove :category_id
      remove :is_anonymous
      remove :allow_comments
      remove :signature_count
      modify :status, :text, default: nil
      add :category, :text
      add :trending, :boolean, default: false
    end

    drop_if_exists unique_index(:signature, [:petition_id, :user_id],
                     name: "signature_unique_signature_index"
                   )

    drop constraint(:signature, "signature_petition_id_fkey")

    drop constraint(:signature, "signature_user_id_fkey")

    drop table(:signature)

    alter table(:users) do
      remove :graduation_year
      remove :student_id
    end
  end
end
