defmodule Petitionu.Repo.Migrations.RemoveSignatureCountAttribute do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:petition) do
      remove :signature_count
    end
  end

  def down do
    alter table(:petition) do
      add :signature_count, :bigint, default: 0
    end
  end
end
