defmodule Petitionu.Repo.Migrations.AddDeadline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:petition) do
      add :deadline, :utc_datetime
    end
  end

  def down do
    alter table(:petition) do
      remove :deadline
    end
  end
end
