defmodule Petitionu.Repo.Migrations.AddPetition do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:petition, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text
      add :body, :text
      add :status, :text
      add :created_at, :utc_datetime_usec
      add :updated_at, :utc_datetime_usec
    end
  end

  def down do
    drop table(:petition)
  end
end
