defmodule Petitionu.Repo.Migrations.VerifySchoolRegistry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organization) do
      add :verification_status, :text, null: false, default: "pending"
      add :registry_name, :text
      add :registry_source, :text
      add :registry_checked_at, :utc_datetime_usec
      add :registry_error, :text
    end

    execute "UPDATE organization SET verification_status = 'approved'"

    alter table(:users) do
      add :pending_organization_id,
          references(:organization,
            column: :id,
            name: "users_pending_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:users, "users_pending_organization_id_fkey")

    alter table(:users) do
      remove :pending_organization_id
    end

    alter table(:organization) do
      remove :registry_error
      remove :registry_checked_at
      remove :registry_source
      remove :registry_name
      remove :verification_status
    end
  end
end
