defmodule Petitionu.Repo.Migrations.Moderation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:content_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :target_title, :text, null: false
      add :target_text, :text, null: false
      add :reason, :text, null: false
      add :details, :text
      add :state, :text, null: false, default: "open"
      add :resolution_note, :text
      add :resolved_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :petition_id,
          references(:petition,
            column: :id,
            name: "content_reports_petition_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :comment_id,
          references(:comment,
            column: :id,
            name: "content_reports_comment_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :organization_id,
          references(:organization,
            column: :id,
            name: "content_reports_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :reporter_id,
          references(:users,
            column: :id,
            name: "content_reports_reporter_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :resolver_id,
          references(:users,
            column: :id,
            name: "content_reports_resolver_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:support_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :requester_email, :citext, null: false
      add :kind, :text, null: false
      add :message, :text, null: false
      add :state, :text, null: false, default: "open"
      add :resolution_note, :text
      add :resolved_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "support_requests_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organization,
            column: :id,
            name: "support_requests_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :resolver_id,
          references(:users,
            column: :id,
            name: "support_requests_resolver_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:support_requests, "support_requests_resolver_id_fkey")

    drop constraint(:support_requests, "support_requests_organization_id_fkey")

    drop constraint(:support_requests, "support_requests_user_id_fkey")

    drop table(:support_requests)

    drop constraint(:content_reports, "content_reports_resolver_id_fkey")

    drop constraint(:content_reports, "content_reports_reporter_id_fkey")

    drop constraint(:content_reports, "content_reports_organization_id_fkey")

    drop constraint(:content_reports, "content_reports_comment_id_fkey")

    drop constraint(:content_reports, "content_reports_petition_id_fkey")

    drop table(:content_reports)
  end
end
