defmodule Petitionu.Repo.Migrations.SecureParticipation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:comment) do
      add :hidden_at, :utc_datetime_usec
    end

    alter table(:petition) do
      add :hidden_at, :utc_datetime_usec

      add :organization_id,
          references(:organization,
            column: :id,
            name: "petition_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:signature) do
      modify :is_verified, :boolean, default: false
    end
  end

  def down do
    alter table(:signature) do
      modify :is_verified, :boolean, default: true
    end

    drop constraint(:petition, "petition_organization_id_fkey")

    alter table(:petition) do
      remove :organization_id
      remove :hidden_at
    end

    alter table(:comment) do
      remove :hidden_at
    end
  end
end
