defmodule Petitionu.Repo.Migrations.AssignSchoolOrganizations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organization) do
      modify :domain, :citext
    end

    execute "UPDATE organization SET domain = NULLIF(lower(btrim(domain::text)), '')"

    create unique_index(:organization, [:domain], name: "organization_unique_domain_index")
  end

  def down do
    alter table(:organization) do
      modify :domain, :text
    end

    drop_if_exists unique_index(:organization, [:domain],
                     name: "organization_unique_domain_index"
                   )
  end
end
